import { Lang } from "./i18n";

export type ContactContent = {
  pageTitle: string;
  pageSubtitle: string;
  faqHeading: string;
  stillNeedHelpHeading: string;
  stillNeedHelpBody: string;
  emailButton: string;
  responseTime: string;
  faq: { q: string; a: string }[];
};

export const CONTACT: Record<Lang, ContactContent> = {
  en: {
    pageTitle: "Contact & FAQ",
    pageSubtitle: "Common questions, and how to reach us if you can't find what you're looking for.",
    faqHeading: "Frequently asked questions",
    stillNeedHelpHeading: "Still need help?",
    stillNeedHelpBody: "If your question isn't answered here, email us directly — we read every message.",
    emailButton: "Email support",
    responseTime: "We usually reply within 24–48 hours.",
    faq: [
      {
        q: "What is Gadit?",
        a: "Gadit is an AI-powered dictionary that goes beyond definitions. You get clear meanings, real-life examples, etymology, idioms, kid-friendly explanations, AI-generated images, sentence practice with feedback, and short quizzes — in many languages.",
      },
      {
        q: "Which languages does Gadit support?",
        a: "You can look up words in any language. The interface currently supports English, Hebrew, Arabic, Russian, Spanish, Portuguese, and French — with more on the way.",
      },
      {
        q: "How is Gadit different from Google or a regular dictionary?",
        a: "Google answers a query. Gadit helps you truly understand a word — all its meanings (including homonyms), its origin and history, idioms that use it, how it feels in a sentence, and lets you practice using it yourself.",
      },
      {
        q: "Do I need an account to use Gadit?",
        a: "No. Basic searches work without signing in. An account unlocks your search history, Kids-friendly explanations, image generation, sentence practice, and (on Deep) quizzes.",
      },
      {
        q: "What do the Clear and Deep plans include?",
        a: "Basic is free and gives you clear meanings, examples, and etymology. Clear adds: kid-friendly explanations, idioms, AI images, your own sentence practice with feedback, voice input, and search history. Deep adds interactive quizzes to cement what you learn.",
      },
      {
        q: "How do I cancel my subscription?",
        a: "Open your Account page and click \"Manage subscription\" — it takes you to the Stripe billing portal where you can cancel anytime. You keep access until the end of your current billing period.",
      },
      {
        q: "Do you offer refunds?",
        a: "Payments are non-refundable except where required by law. If you were charged in error, email us within 30 days and we'll sort it out.",
      },
      {
        q: "Is Gadit safe for kids?",
        a: "Kids Mode gives child-friendly explanations for every meaning. The service is intended for users 13 and older — if a child under 13 has made an account, let us know and we'll remove it.",
      },
      {
        q: "How accurate are Gadit's definitions?",
        a: "Definitions are generated by advanced AI models and are generally high quality, but AI can occasionally be incomplete or mistaken. For academic or professional decisions, cross-check with an authoritative dictionary.",
      },
      {
        q: "Are the AI-generated images always accurate?",
        a: "Images are visual hints to help remember a word — not literal depictions. They can sometimes be unexpected. If you get a weird image, try again, or add a context sentence.",
      },
      {
        q: "What happens to my data and search history?",
        a: "Your account data, search history (up to 10 recent words), and generated images are stored securely on Google Firebase. We never sell your data. For details, see our Privacy Policy.",
      },
      {
        q: "How do I delete my account?",
        a: "Email us at the address below and we'll delete your account and associated data within 30 days.",
      },
    ],
  },

  he: {
    pageTitle: "יצירת קשר ושאלות נפוצות",
    pageSubtitle: "שאלות נפוצות, ואיך אפשר לפנות אלינו אם לא מצאתם את מה שחיפשתם.",
    faqHeading: "שאלות נפוצות",
    stillNeedHelpHeading: "עדיין צריכים עזרה?",
    stillNeedHelpBody: "אם השאלה שלכם לא מופיעה כאן, פשוט כתבו לנו — אנחנו קוראים כל הודעה.",
    emailButton: "שליחת מייל לתמיכה",
    responseTime: "בדרך כלל אנחנו חוזרים תוך 24–48 שעות.",
    faq: [
      {
        q: "מה זה Gadit?",
        a: "Gadit הוא מילון מבוסס AI שהולך רחוק מעבר להגדרות. מקבלים משמעויות ברורות, דוגמאות מהחיים, אטימולוגיה, ניבים, הסבר ידידותי לילדים, תמונות שנוצרות ב-AI, תרגול משפטים עם פידבק, וחידונים קצרים — בהרבה שפות.",
      },
      {
        q: "באילו שפות Gadit תומך?",
        a: "אפשר לחפש מילים בכל שפה. הממשק תומך כרגע באנגלית, עברית, ערבית, רוסית, ספרדית, פורטוגזית וצרפתית — ועוד בדרך.",
      },
      {
        q: "במה Gadit שונה מגוגל או ממילון רגיל?",
        a: "גוגל עונה על חיפוש. Gadit עוזר להבין מילה באמת — את כל המשמעויות שלה (כולל הומונימים), את המקור וההיסטוריה, ניבים שמשתמשים בה, איך היא מרגישה במשפט, ונותן לתרגל להשתמש בה בעצמכם.",
      },
      {
        q: "צריך חשבון כדי להשתמש ב-Gadit?",
        a: "לא. חיפושים בסיסיים עובדים בלי התחברות. חשבון פותח את היסטוריית החיפושים, הסברים ידידותיים לילדים, יצירת תמונות, תרגול משפטים, ו(בתוכנית Deep) חידונים.",
      },
      {
        q: "מה כולל Clear ו-Deep?",
        a: "Basic הוא חינמי וכולל משמעויות ברורות, דוגמאות ואטימולוגיה. Clear מוסיף: הסברים ידידותיים לילדים, ניבים, תמונות AI, תרגול משפטים עם פידבק, קלט קולי והיסטוריית חיפושים. Deep מוסיף חידונים אינטראקטיביים כדי להטמיע את מה שלמדתם.",
      },
      {
        q: "איך מבטלים מנוי?",
        a: "נכנסים לדף החשבון ולוחצים על \"ניהול מנוי\" — זה מעביר לפורטל החיוב של Stripe שם אפשר לבטל בכל רגע. הגישה נשמרת עד סוף תקופת החיוב הנוכחית.",
      },
      {
        q: "האם יש החזרים?",
        a: "התשלומים אינם ניתנים להחזרה, למעט במקרים שבהם החוק מחייב אחרת. אם חויבתם בטעות, כתבו לנו תוך 30 יום ונסדר את זה.",
      },
      {
        q: "האם Gadit בטוח לילדים?",
        a: "מצב ילדים מציג הסבר ידידותי לכל משמעות. השירות מיועד לגיל 13 ומעלה — אם ילד מתחת לגיל 13 פתח חשבון, כתבו לנו ואנחנו נסיר אותו.",
      },
      {
        q: "עד כמה ההגדרות של Gadit מדויקות?",
        a: "ההגדרות נוצרות על ידי מודלי AI מתקדמים ובדרך כלל באיכות גבוהה, אבל AI עשוי לפעמים להיות חלקי או שגוי. להחלטות אקדמיות או מקצועיות, כדאי להצליב עם מילון מוסמך.",
      },
      {
        q: "האם התמונות שנוצרות תמיד מדויקות?",
        a: "התמונות הן רמזים ויזואליים שעוזרים לזכור מילה — לא ייצוגים מילוליים. לפעמים הן יכולות להיות מפתיעות. אם קיבלתם תמונה מוזרה, נסו שוב או הוסיפו משפט הקשר.",
      },
      {
        q: "מה קורה למידע ולהיסטוריית החיפוש שלי?",
        a: "נתוני החשבון, היסטוריית החיפוש (עד 10 מילים אחרונות), והתמונות שנוצרו נשמרים באופן מאובטח ב-Google Firebase. אנחנו לא מוכרים את המידע שלכם. לפרטים, ראו את מדיניות הפרטיות.",
      },
      {
        q: "איך מוחקים חשבון?",
        a: "שלחו לנו מייל לכתובת למטה ואנחנו נמחק את החשבון ואת המידע הנלווה תוך 30 יום.",
      },
    ],
  },

  ar: {
    pageTitle: "الاتصال والأسئلة الشائعة",
    pageSubtitle: "الأسئلة الشائعة، وكيف يمكنك التواصل معنا إذا لم تجد ما تبحث عنه.",
    faqHeading: "الأسئلة الشائعة",
    stillNeedHelpHeading: "ما زلت بحاجة إلى المساعدة؟",
    stillNeedHelpBody: "إذا لم تجد إجابة سؤالك هنا، راسلنا مباشرةً — نحن نقرأ كل رسالة.",
    emailButton: "مراسلة الدعم",
    responseTime: "نرد عادةً خلال 24–48 ساعة.",
    faq: [
      {
        q: "ما هو Gadit؟",
        a: "Gadit هو قاموس مدعوم بالذكاء الاصطناعي يتجاوز مجرد التعريفات. تحصل على معانٍ واضحة وأمثلة من الحياة الواقعية وعلم الاشتقاق والتعابير الاصطلاحية وشروحات مناسبة للأطفال وصور مُولَّدة بالذكاء الاصطناعي وتدريب على الجمل مع تغذية راجعة واختبارات قصيرة — بعدة لغات.",
      },
      {
        q: "ما اللغات التي يدعمها Gadit؟",
        a: "يمكنك البحث عن الكلمات بأي لغة. تدعم الواجهة حاليًا الإنجليزية والعبرية والعربية والروسية والإسبانية والبرتغالية والفرنسية — والمزيد قادم.",
      },
      {
        q: "كيف يختلف Gadit عن Google أو قاموس عادي؟",
        a: "Google يجيب على استفسار. Gadit يساعدك على فهم الكلمة حقًا — جميع معانيها (بما في ذلك الكلمات المتجانسة)، وأصلها وتاريخها، والتعابير التي تستخدمها، وكيف تبدو في جملة، ويتيح لك ممارسة استخدامها بنفسك.",
      },
      {
        q: "هل أحتاج إلى حساب لاستخدام Gadit؟",
        a: "لا. تعمل عمليات البحث الأساسية بدون تسجيل دخول. يمنحك الحساب الوصول إلى سجل البحث والشروحات المناسبة للأطفال وتوليد الصور والتدريب على الجمل والاختبارات (في خطة Deep).",
      },
      {
        q: "ماذا تتضمن خطتا Clear و Deep؟",
        a: "الخطة الأساسية (Basic) مجانية وتقدم معاني واضحة وأمثلة وعلم اشتقاق. تضيف Clear: شروحات للأطفال، تعابير اصطلاحية، صور AI، تدريب على جملك الخاصة مع تغذية راجعة، الإدخال الصوتي، وسجل البحث. تضيف Deep اختبارات تفاعلية لتثبيت ما تعلمته.",
      },
      {
        q: "كيف ألغي اشتراكي؟",
        a: "افتح صفحة حسابك وانقر على \"إدارة الاشتراك\" — سينقلك ذلك إلى بوابة الفوترة في Stripe حيث يمكنك الإلغاء في أي وقت. ستحتفظ بالوصول حتى نهاية فترة الفوترة الحالية.",
      },
      {
        q: "هل تقدمون استردادًا للأموال؟",
        a: "المدفوعات غير قابلة للاسترداد إلا عندما يتطلب القانون ذلك. إذا تم تحصيل رسوم منك عن طريق الخطأ، راسلنا خلال 30 يومًا وسنحل الأمر.",
      },
      {
        q: "هل Gadit آمن للأطفال؟",
        a: "وضع الأطفال يقدم شروحات مناسبة للأطفال لكل معنى. الخدمة مخصصة للمستخدمين من عمر 13 عامًا فما فوق — إذا أنشأ طفل دون سن 13 حسابًا، أخبرنا وسنحذفه.",
      },
      {
        q: "ما مدى دقة تعريفات Gadit؟",
        a: "تُولَّد التعريفات بواسطة نماذج ذكاء اصطناعي متقدمة وتكون عادةً عالية الجودة، ولكن قد يكون الذكاء الاصطناعي أحيانًا غير مكتمل أو مخطئًا. للقرارات الأكاديمية أو المهنية، تحقق من قاموس موثوق.",
      },
      {
        q: "هل الصور المولدة بالذكاء الاصطناعي دقيقة دائمًا؟",
        a: "الصور هي تلميحات بصرية لمساعدتك في تذكّر الكلمة — وليست تصويرًا حرفيًا. قد تكون مفاجئة أحيانًا. إذا حصلت على صورة غريبة، فحاول مرة أخرى أو أضف جملة سياقية.",
      },
      {
        q: "ماذا يحدث لبياناتي وسجل البحث الخاص بي؟",
        a: "يتم تخزين بيانات حسابك وسجل البحث (ما يصل إلى 10 كلمات حديثة) والصور المولدة بأمان على Google Firebase. نحن لا نبيع بياناتك أبدًا. للتفاصيل، راجع سياسة الخصوصية.",
      },
      {
        q: "كيف أحذف حسابي؟",
        a: "راسلنا على العنوان أدناه وسنحذف حسابك والبيانات المرتبطة به خلال 30 يومًا.",
      },
    ],
  },

  ru: {
    pageTitle: "Контакты и частые вопросы",
    pageSubtitle: "Часто задаваемые вопросы и как с нами связаться, если вы не нашли ответ.",
    faqHeading: "Часто задаваемые вопросы",
    stillNeedHelpHeading: "Нужна ещё помощь?",
    stillNeedHelpBody: "Если вашего вопроса нет здесь, напишите нам напрямую — мы читаем каждое сообщение.",
    emailButton: "Написать в поддержку",
    responseTime: "Обычно отвечаем в течение 24–48 часов.",
    faq: [
      {
        q: "Что такое Gadit?",
        a: "Gadit — это словарь на базе ИИ, который идёт дальше простых определений. Вы получаете ясные значения, живые примеры, этимологию, идиомы, объяснения для детей, изображения, сгенерированные ИИ, практику предложений с обратной связью и короткие викторины — на многих языках.",
      },
      {
        q: "Какие языки поддерживает Gadit?",
        a: "Искать слова можно на любом языке. Интерфейс сейчас поддерживает английский, иврит, арабский, русский, испанский, португальский и французский — и добавятся ещё.",
      },
      {
        q: "Чем Gadit отличается от Google или обычного словаря?",
        a: "Google отвечает на запрос. Gadit помогает по-настоящему понять слово — все его значения (включая омонимы), происхождение и историю, идиомы с ним, как оно ощущается в предложении, и позволяет попрактиковаться самому.",
      },
      {
        q: "Нужен ли аккаунт, чтобы пользоваться Gadit?",
        a: "Нет. Базовый поиск работает без входа. Аккаунт открывает историю поиска, объяснения для детей, генерацию изображений, практику предложений и (на тарифе Deep) викторины.",
      },
      {
        q: "Что входит в планы Clear и Deep?",
        a: "Basic бесплатный и даёт ясные значения, примеры и этимологию. Clear добавляет: объяснения для детей, идиомы, изображения ИИ, практику собственных предложений с обратной связью, голосовой ввод и историю поиска. Deep добавляет интерактивные викторины для закрепления материала.",
      },
      {
        q: "Как отменить подписку?",
        a: "Откройте страницу аккаунта и нажмите «Управлять подпиской» — это откроет портал Stripe, где можно отменить в любой момент. Доступ сохраняется до конца текущего периода оплаты.",
      },
      {
        q: "Делаете ли вы возврат средств?",
        a: "Платежи не подлежат возврату, за исключением случаев, предусмотренных законом. Если с вас списали по ошибке, напишите нам в течение 30 дней, и мы разберёмся.",
      },
      {
        q: "Безопасен ли Gadit для детей?",
        a: "Детский режим показывает понятные детям объяснения для каждого значения. Сервис предназначен для пользователей от 13 лет — если ребёнок до 13 создал аккаунт, сообщите нам, и мы его удалим.",
      },
      {
        q: "Насколько точны определения Gadit?",
        a: "Определения создаются передовыми моделями ИИ и обычно высокого качества, но ИИ иногда может ошибаться или быть неполным. Для академических или профессиональных решений сверяйтесь с авторитетным словарём.",
      },
      {
        q: "Всегда ли точны сгенерированные изображения?",
        a: "Изображения — это визуальные подсказки, помогающие запомнить слово, а не буквальные иллюстрации. Иногда они могут быть неожиданными. Если картинка странная, попробуйте ещё раз или добавьте контекстное предложение.",
      },
      {
        q: "Что происходит с моими данными и историей поиска?",
        a: "Данные аккаунта, история поиска (до 10 недавних слов) и сгенерированные изображения надёжно хранятся на Google Firebase. Мы никогда не продаём ваши данные. Подробнее — в Политике конфиденциальности.",
      },
      {
        q: "Как удалить аккаунт?",
        a: "Напишите нам по адресу ниже, и мы удалим ваш аккаунт и связанные данные в течение 30 дней.",
      },
    ],
  },

  es: {
    pageTitle: "Contacto y preguntas frecuentes",
    pageSubtitle: "Preguntas comunes y cómo comunicarte con nosotros si no encuentras lo que buscas.",
    faqHeading: "Preguntas frecuentes",
    stillNeedHelpHeading: "¿Todavía necesitas ayuda?",
    stillNeedHelpBody: "Si tu pregunta no está aquí, escríbenos directamente: leemos cada mensaje.",
    emailButton: "Escribir a soporte",
    responseTime: "Solemos responder en 24–48 horas.",
    faq: [
      {
        q: "¿Qué es Gadit?",
        a: "Gadit es un diccionario impulsado por IA que va más allá de las definiciones. Obtienes significados claros, ejemplos de la vida real, etimología, modismos, explicaciones para niños, imágenes generadas por IA, práctica de oraciones con retroalimentación y cuestionarios breves, en muchos idiomas.",
      },
      {
        q: "¿Qué idiomas admite Gadit?",
        a: "Puedes buscar palabras en cualquier idioma. La interfaz actualmente admite inglés, hebreo, árabe, ruso, español, portugués y francés, y habrá más.",
      },
      {
        q: "¿En qué se diferencia Gadit de Google o de un diccionario común?",
        a: "Google responde a una consulta. Gadit te ayuda a entender realmente una palabra: todos sus significados (incluidos los homónimos), su origen e historia, los modismos que la usan, cómo se siente en una oración, y te permite practicar usándola tú mismo.",
      },
      {
        q: "¿Necesito una cuenta para usar Gadit?",
        a: "No. Las búsquedas básicas funcionan sin iniciar sesión. Una cuenta desbloquea tu historial de búsqueda, las explicaciones para niños, la generación de imágenes, la práctica de oraciones y (en Deep) los cuestionarios.",
      },
      {
        q: "¿Qué incluyen los planes Clear y Deep?",
        a: "Basic es gratis y ofrece significados claros, ejemplos y etimología. Clear añade: explicaciones para niños, modismos, imágenes de IA, práctica de tus propias oraciones con retroalimentación, entrada por voz e historial de búsqueda. Deep añade cuestionarios interactivos para afianzar lo aprendido.",
      },
      {
        q: "¿Cómo cancelo mi suscripción?",
        a: "Abre tu página de cuenta y haz clic en «Gestionar suscripción»: te lleva al portal de facturación de Stripe, donde puedes cancelar en cualquier momento. Mantienes el acceso hasta el final del período de facturación actual.",
      },
      {
        q: "¿Ofrecen reembolsos?",
        a: "Los pagos no son reembolsables, salvo cuando la ley lo exija. Si te cobraron por error, escríbenos dentro de 30 días y lo resolveremos.",
      },
      {
        q: "¿Es Gadit seguro para niños?",
        a: "El modo para niños ofrece explicaciones comprensibles para cada significado. El servicio está pensado para mayores de 13 años: si un menor de 13 ha creado una cuenta, avísanos y la eliminaremos.",
      },
      {
        q: "¿Qué tan precisas son las definiciones de Gadit?",
        a: "Las definiciones las generan modelos de IA avanzados y suelen ser de alta calidad, pero la IA puede a veces estar incompleta o equivocarse. Para decisiones académicas o profesionales, contrástalas con un diccionario de referencia.",
      },
      {
        q: "¿Las imágenes generadas por IA son siempre precisas?",
        a: "Las imágenes son pistas visuales que ayudan a recordar una palabra; no son representaciones literales. A veces pueden ser inesperadas. Si obtienes una imagen rara, inténtalo de nuevo o añade una oración de contexto.",
      },
      {
        q: "¿Qué pasa con mis datos y mi historial de búsqueda?",
        a: "Los datos de tu cuenta, tu historial de búsqueda (hasta 10 palabras recientes) y las imágenes generadas se almacenan de forma segura en Google Firebase. Nunca vendemos tus datos. Para más detalles, consulta nuestra Política de Privacidad.",
      },
      {
        q: "¿Cómo elimino mi cuenta?",
        a: "Escríbenos a la dirección de abajo y eliminaremos tu cuenta y los datos asociados en un plazo de 30 días.",
      },
    ],
  },

  pt: {
    pageTitle: "Contato e perguntas frequentes",
    pageSubtitle: "Perguntas comuns e como falar conosco se você não encontrar o que procura.",
    faqHeading: "Perguntas frequentes",
    stillNeedHelpHeading: "Ainda precisa de ajuda?",
    stillNeedHelpBody: "Se sua pergunta não está aqui, escreva para a gente: lemos todas as mensagens.",
    emailButton: "Enviar e-mail ao suporte",
    responseTime: "Costumamos responder em 24–48 horas.",
    faq: [
      {
        q: "O que é o Gadit?",
        a: "O Gadit é um dicionário com IA que vai além das definições. Você recebe significados claros, exemplos do dia a dia, etimologia, expressões idiomáticas, explicações para crianças, imagens geradas por IA, prática de frases com feedback e quizzes curtos — em vários idiomas.",
      },
      {
        q: "Quais idiomas o Gadit suporta?",
        a: "Você pode buscar palavras em qualquer idioma. A interface atualmente oferece inglês, hebraico, árabe, russo, espanhol, português e francês — com mais a caminho.",
      },
      {
        q: "Como o Gadit é diferente do Google ou de um dicionário comum?",
        a: "O Google responde a uma consulta. O Gadit ajuda você a entender de verdade uma palavra: todos os seus significados (incluindo homônimos), sua origem e história, expressões idiomáticas que a usam, como ela soa em uma frase, e permite que você pratique usando-a.",
      },
      {
        q: "Preciso de uma conta para usar o Gadit?",
        a: "Não. Buscas básicas funcionam sem login. Uma conta libera o histórico de buscas, explicações para crianças, geração de imagens, prática de frases e (no plano Deep) quizzes.",
      },
      {
        q: "O que os planos Clear e Deep incluem?",
        a: "Basic é gratuito e oferece significados claros, exemplos e etimologia. Clear adiciona: explicações para crianças, expressões idiomáticas, imagens de IA, prática de suas próprias frases com feedback, entrada de voz e histórico de buscas. Deep adiciona quizzes interativos para fixar o que você aprendeu.",
      },
      {
        q: "Como cancelo minha assinatura?",
        a: "Abra sua página de conta e clique em \"Gerenciar assinatura\" — isso leva você ao portal de cobrança da Stripe, onde pode cancelar a qualquer momento. O acesso continua até o fim do período de cobrança atual.",
      },
      {
        q: "Vocês oferecem reembolso?",
        a: "Os pagamentos não são reembolsáveis, exceto quando a lei exigir. Se você foi cobrado por engano, escreva para a gente em até 30 dias e resolvemos.",
      },
      {
        q: "O Gadit é seguro para crianças?",
        a: "O Modo Crianças traz explicações acessíveis para cada significado. O serviço é destinado a usuários a partir de 13 anos — se uma criança menor de 13 criou uma conta, avise-nos e a removeremos.",
      },
      {
        q: "Quão precisas são as definições do Gadit?",
        a: "As definições são geradas por modelos de IA avançados e geralmente têm alta qualidade, mas a IA pode, às vezes, ser incompleta ou errar. Para decisões acadêmicas ou profissionais, confira em um dicionário de referência.",
      },
      {
        q: "As imagens geradas por IA são sempre precisas?",
        a: "As imagens são dicas visuais para ajudar a lembrar uma palavra — não são representações literais. Podem ser inesperadas às vezes. Se receber uma imagem estranha, tente novamente ou adicione uma frase de contexto.",
      },
      {
        q: "O que acontece com meus dados e meu histórico de buscas?",
        a: "Os dados da sua conta, o histórico de buscas (até 10 palavras recentes) e as imagens geradas ficam armazenados com segurança no Google Firebase. Nunca vendemos seus dados. Para detalhes, veja a Política de Privacidade.",
      },
      {
        q: "Como excluo minha conta?",
        a: "Escreva para o endereço abaixo e excluiremos sua conta e os dados associados em até 30 dias.",
      },
    ],
  },

  fr: {
    pageTitle: "Contact et questions fréquentes",
    pageSubtitle: "Questions courantes et comment nous contacter si vous ne trouvez pas ce que vous cherchez.",
    faqHeading: "Foire aux questions",
    stillNeedHelpHeading: "Besoin d'aide supplémentaire ?",
    stillNeedHelpBody: "Si votre question n'a pas de réponse ici, écrivez-nous directement — nous lisons chaque message.",
    emailButton: "Contacter le support",
    responseTime: "Nous répondons généralement sous 24 à 48 heures.",
    faq: [
      {
        q: "Qu'est-ce que Gadit ?",
        a: "Gadit est un dictionnaire propulsé par l'IA qui va au-delà des définitions. Vous obtenez des significations claires, des exemples de la vie réelle, l'étymologie, des expressions idiomatiques, des explications pour enfants, des images générées par l'IA, un entraînement aux phrases avec retour et de courts quiz — dans de nombreuses langues.",
      },
      {
        q: "Quelles langues Gadit prend-il en charge ?",
        a: "Vous pouvez chercher des mots dans n'importe quelle langue. L'interface prend actuellement en charge l'anglais, l'hébreu, l'arabe, le russe, l'espagnol, le portugais et le français — et d'autres arrivent.",
      },
      {
        q: "En quoi Gadit est-il différent de Google ou d'un dictionnaire classique ?",
        a: "Google répond à une requête. Gadit vous aide à vraiment comprendre un mot : tous ses sens (y compris les homonymes), son origine et son histoire, les expressions qui l'utilisent, ce qu'il donne dans une phrase, et vous permet de vous entraîner à l'utiliser vous-même.",
      },
      {
        q: "Ai-je besoin d'un compte pour utiliser Gadit ?",
        a: "Non. Les recherches de base fonctionnent sans connexion. Un compte débloque l'historique de recherche, les explications pour enfants, la génération d'images, l'entraînement aux phrases et (avec Deep) les quiz.",
      },
      {
        q: "Que contiennent les formules Clear et Deep ?",
        a: "Basic est gratuit et propose des significations claires, des exemples et l'étymologie. Clear ajoute : explications pour enfants, expressions, images IA, entraînement sur vos propres phrases avec retour, saisie vocale et historique. Deep ajoute des quiz interactifs pour consolider ce que vous avez appris.",
      },
      {
        q: "Comment annuler mon abonnement ?",
        a: "Ouvrez votre page de compte et cliquez sur « Gérer l'abonnement » — cela vous dirige vers le portail de facturation Stripe où vous pouvez annuler à tout moment. Vous conservez l'accès jusqu'à la fin de la période de facturation en cours.",
      },
      {
        q: "Proposez-vous des remboursements ?",
        a: "Les paiements ne sont pas remboursables, sauf si la loi l'exige. En cas d'erreur de facturation, écrivez-nous dans les 30 jours et nous réglerons cela.",
      },
      {
        q: "Gadit est-il adapté aux enfants ?",
        a: "Le Mode Enfants fournit des explications adaptées pour chaque sens. Le service est destiné aux utilisateurs de 13 ans et plus — si un enfant de moins de 13 ans a créé un compte, dites-le-nous et nous le supprimerons.",
      },
      {
        q: "Quelle est la précision des définitions de Gadit ?",
        a: "Les définitions sont générées par des modèles d'IA avancés et sont généralement de haute qualité, mais l'IA peut parfois être incomplète ou se tromper. Pour des décisions académiques ou professionnelles, vérifiez avec un dictionnaire de référence.",
      },
      {
        q: "Les images générées par l'IA sont-elles toujours exactes ?",
        a: "Les images sont des indices visuels pour aider à retenir un mot — pas des représentations littérales. Elles peuvent parfois être inattendues. Si vous obtenez une image étrange, réessayez ou ajoutez une phrase de contexte.",
      },
      {
        q: "Que deviennent mes données et mon historique de recherche ?",
        a: "Les données de votre compte, votre historique (jusqu'à 10 mots récents) et les images générées sont stockés en toute sécurité sur Google Firebase. Nous ne vendons jamais vos données. Pour plus de détails, consultez notre Politique de confidentialité.",
      },
      {
        q: "Comment supprimer mon compte ?",
        a: "Écrivez-nous à l'adresse ci-dessous et nous supprimerons votre compte et les données associées dans un délai de 30 jours.",
      },
    ],
  },
};
