import type { RankKey } from "./gamification";

/**
 * Localized copy for the kids gamification widgets, in all 22 UI languages
 * (Gadi 2026-08-13: make the whole kids experience native everywhere, like
 * the rest of the app — it sits right next to "אוצר המילים שלי"). Kept out
 * of the pure gamification module so that stays i/o- and i18n-free. English
 * is the fallback for any code not listed. Never translates "Gadit".
 */

export const RANK_LABELS: Record<string, Record<RankKey, string>> = {
  en: { scout: "Word Scout", explorer: "Word Explorer", tracker: "Word Tracker", ranger: "Word Ranger", guide: "Word Guide", master: "Word Master" },
  he: { scout: "מגלה מתחיל", explorer: "מגלה מילים", tracker: "חוקר מילים", ranger: "מגלה מנוסה", guide: "מדריך מילים", master: "אלוף המילים" },
  ar: { scout: "مستكشف مبتدئ", explorer: "مستكشف كلمات", tracker: "باحث كلمات", ranger: "مستكشف متمرّس", guide: "مرشد كلمات", master: "بطل الكلمات" },
  ru: { scout: "Юный искатель", explorer: "Искатель слов", tracker: "Следопыт слов", ranger: "Опытный искатель", guide: "Проводник слов", master: "Мастер слов" },
  es: { scout: "Explorador novato", explorer: "Explorador de palabras", tracker: "Rastreador de palabras", ranger: "Explorador experto", guide: "Guía de palabras", master: "Maestro de palabras" },
  pt: { scout: "Explorador iniciante", explorer: "Explorador de palavras", tracker: "Rastreador de palavras", ranger: "Explorador experiente", guide: "Guia de palavras", master: "Mestre das palavras" },
  fr: { scout: "Éclaireur des mots", explorer: "Explorateur de mots", tracker: "Traqueur de mots", ranger: "Explorateur chevronné", guide: "Guide des mots", master: "Maître des mots" },
  de: { scout: "Wort-Späher", explorer: "Wort-Entdecker", tracker: "Wort-Spurenleser", ranger: "Erfahrener Entdecker", guide: "Wort-Guide", master: "Wort-Meister" },
  cs: { scout: "Začínající objevitel", explorer: "Objevitel slov", tracker: "Stopař slov", ranger: "Zkušený objevitel", guide: "Průvodce slovy", master: "Mistr slov" },
  sk: { scout: "Začínajúci objaviteľ", explorer: "Objaviteľ slov", tracker: "Stopár slov", ranger: "Skúsený objaviteľ", guide: "Sprievodca slovami", master: "Majster slov" },
  it: { scout: "Esploratore alle prime armi", explorer: "Esploratore di parole", tracker: "Cercatore di parole", ranger: "Esploratore esperto", guide: "Guida delle parole", master: "Maestro delle parole" },
  ja: { scout: "ことばの見習い", explorer: "ことばの探検家", tracker: "ことばの追跡者", ranger: "ベテラン探検家", guide: "ことばの案内人", master: "ことばの達人" },
  hi: { scout: "नौसिखिया खोजी", explorer: "शब्द खोजी", tracker: "शब्द अन्वेषक", ranger: "अनुभवी खोजी", guide: "शब्द मार्गदर्शक", master: "शब्द माहिर" },
  am: { scout: "ጀማሪ አሳሽ", explorer: "የቃላት አሳሽ", tracker: "የቃላት መርማሪ", ranger: "የተካነ አሳሽ", guide: "የቃላት መሪ", master: "የቃላት ጌታ" },
  uk: { scout: "Юний шукач", explorer: "Шукач слів", tracker: "Слідопит слів", ranger: "Досвідчений шукач", guide: "Провідник слів", master: "Майстер слів" },
  tr: { scout: "Acemi kâşif", explorer: "Kelime kâşifi", tracker: "Kelime izcisi", ranger: "Deneyimli kâşif", guide: "Kelime rehberi", master: "Kelime ustası" },
  pl: { scout: "Początkujący odkrywca", explorer: "Odkrywca słów", tracker: "Tropiciel słów", ranger: "Doświadczony odkrywca", guide: "Przewodnik po słowach", master: "Mistrz słów" },
  fa: { scout: "کاوشگر تازه‌کار", explorer: "کاوشگر واژه‌ها", tracker: "ردیاب واژه‌ها", ranger: "کاوشگر باتجربه", guide: "راهنمای واژه‌ها", master: "استاد واژه‌ها" },
  id: { scout: "Penjelajah pemula", explorer: "Penjelajah kata", tracker: "Pelacak kata", ranger: "Penjelajah berpengalaman", guide: "Pemandu kata", master: "Ahli kata" },
  nl: { scout: "Beginnende verkenner", explorer: "Woordverkenner", tracker: "Woordspeurder", ranger: "Ervaren verkenner", guide: "Woordgids", master: "Woordmeester" },
  el: { scout: "Αρχάριος εξερευνητής", explorer: "Εξερευνητής λέξεων", tracker: "Ιχνηλάτης λέξεων", ranger: "Έμπειρος εξερευνητής", guide: "Οδηγός λέξεων", master: "Δεξιοτέχνης λέξεων" },
  zu: { scout: "Umhloli oqalayo", explorer: "Umhloli wamagama", tracker: "Umlandeli wamagama", ranger: "Umhloli onolwazi", guide: "Umholi wamagama", master: "Ingcweti yamagama" },
};

export function rankLabel(key: RankKey, lang: string): string {
  return (RANK_LABELS[lang] ?? RANK_LABELS.en)[key];
}

export type GameCopy = {
  streakTitle: string;
  streakDays: (n: number) => string;
  streakStart: string;
  weeklyTitle: string;
  weeklyProgress: (n: number, goal: number) => string;
  weeklyDone: string;
  rankTitle: string;
  toNext: (n: number) => string;
  topRank: string;
  collected: (n: number) => string;
};

export const GAME_COPY: Record<string, GameCopy> = {
  en: {
    streakTitle: "Streak",
    streakDays: (n) => (n === 1 ? "1 day in a row" : `${n} days in a row`),
    streakStart: "Look up a word to start a streak",
    weeklyTitle: "Weekly goal",
    weeklyProgress: (n, goal) => `${n} / ${goal} new words`,
    weeklyDone: "Goal complete!",
    rankTitle: "Your rank",
    toNext: (n) => (n === 1 ? "1 more word to level up" : `${n} more words to level up`),
    topRank: "Top rank reached!",
    collected: (n) => (n === 1 ? "1 word collected" : `${n} words collected`),
  },
  he: {
    streakTitle: "רצף",
    streakDays: (n) => (n === 1 ? "יום אחד ברצף" : `${n} ימים ברצף`),
    streakStart: "חפשו מילה כדי להתחיל רצף",
    weeklyTitle: "יעד שבועי",
    weeklyProgress: (n, goal) => `${n} / ${goal} מילים חדשות`,
    weeklyDone: "היעד הושלם!",
    rankTitle: "הדרגה שלך",
    toNext: (n) => (n === 1 ? "עוד מילה אחת לדרגה הבאה" : `עוד ${n} מילים לדרגה הבאה`),
    topRank: "הגעת לדרגה הגבוהה ביותר!",
    collected: (n) => (n === 1 ? "מילה אחת באוצר" : `${n} מילים באוצר`),
  },
  ar: {
    streakTitle: "سلسلة",
    streakDays: (n) => (n === 1 ? "يوم واحد متتالٍ" : `${n} أيام متتالية`),
    streakStart: "ابحث عن كلمة لتبدأ سلسلة",
    weeklyTitle: "هذا الأسبوع",
    weeklyProgress: (n, goal) => `${n} / ${goal} كلمات جديدة`,
    weeklyDone: "أكملت هدف الأسبوع!",
    rankTitle: "رتبتك",
    toNext: (n) => (n === 1 ? "كلمة واحدة للترقية" : `${n} كلمات للترقية`),
    topRank: "وصلت إلى أعلى رتبة!",
    collected: (n) => (n === 1 ? "كلمة واحدة في المجموعة" : `${n} كلمات في المجموعة`),
  },
  ru: {
    streakTitle: "Серия",
    streakDays: (n) => (n === 1 ? "1 день подряд" : `${n} дней подряд`),
    streakStart: "Найди слово, чтобы начать серию",
    weeklyTitle: "На этой неделе",
    weeklyProgress: (n, goal) => `${n} / ${goal} новых слов`,
    weeklyDone: "Цель недели выполнена!",
    rankTitle: "Твой ранг",
    toNext: (n) => (n === 1 ? "ещё 1 слово до нового ранга" : `ещё ${n} слов(а) до нового ранга`),
    topRank: "Достигнут высший ранг!",
    collected: (n) => (n === 1 ? "1 слово собрано" : `${n} слов собрано`),
  },
  es: {
    streakTitle: "Racha",
    streakDays: (n) => (n === 1 ? "1 día seguido" : `${n} días seguidos`),
    streakStart: "Busca una palabra para empezar una racha",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palabras nuevas`,
    weeklyDone: "¡Meta de la semana cumplida!",
    rankTitle: "Tu rango",
    toNext: (n) => (n === 1 ? "1 palabra más para subir de nivel" : `${n} palabras más para subir de nivel`),
    topRank: "¡Rango máximo alcanzado!",
    collected: (n) => (n === 1 ? "1 palabra reunida" : `${n} palabras reunidas`),
  },
  pt: {
    streakTitle: "Sequência",
    streakDays: (n) => (n === 1 ? "1 dia seguido" : `${n} dias seguidos`),
    streakStart: "Busque uma palavra para começar uma sequência",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palavras novas`,
    weeklyDone: "Meta da semana concluída!",
    rankTitle: "Seu nível",
    toNext: (n) => (n === 1 ? "mais 1 palavra para subir de nível" : `mais ${n} palavras para subir de nível`),
    topRank: "Nível máximo alcançado!",
    collected: (n) => (n === 1 ? "1 palavra reunida" : `${n} palavras reunidas`),
  },
  fr: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 jour d'affilée" : `${n} jours d'affilée`),
    streakStart: "Cherche un mot pour lancer une série",
    weeklyTitle: "Cette semaine",
    weeklyProgress: (n, goal) => `${n} / ${goal} nouveaux mots`,
    weeklyDone: "Objectif de la semaine atteint !",
    rankTitle: "Ton rang",
    toNext: (n) => (n === 1 ? "encore 1 mot pour monter de niveau" : `encore ${n} mots pour monter de niveau`),
    topRank: "Rang maximal atteint !",
    collected: (n) => (n === 1 ? "1 mot collecté" : `${n} mots collectés`),
  },
  de: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 Tag in Folge" : `${n} Tage in Folge`),
    streakStart: "Schlag ein Wort nach, um eine Serie zu starten",
    weeklyTitle: "Diese Woche",
    weeklyProgress: (n, goal) => `${n} / ${goal} neue Wörter`,
    weeklyDone: "Wochenziel geschafft!",
    rankTitle: "Dein Rang",
    toNext: (n) => (n === 1 ? "noch 1 Wort bis zum nächsten Rang" : `noch ${n} Wörter bis zum nächsten Rang`),
    topRank: "Höchster Rang erreicht!",
    collected: (n) => (n === 1 ? "1 Wort gesammelt" : `${n} Wörter gesammelt`),
  },
  cs: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 den v řadě" : `${n} dní v řadě`),
    streakStart: "Vyhledej slovo a začni sérii",
    weeklyTitle: "Tento týden",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týdenní cíl splněn!",
    rankTitle: "Tvoje úroveň",
    toNext: (n) => (n === 1 ? "ještě 1 slovo do vyšší úrovně" : `ještě ${n} slov do vyšší úrovně`),
    topRank: "Nejvyšší úroveň dosažena!",
    collected: (n) => (n === 1 ? "1 slovo nasbíráno" : `${n} slov nasbíráno`),
  },
  sk: {
    streakTitle: "Séria",
    streakDays: (n) => (n === 1 ? "1 deň v rade" : `${n} dní v rade`),
    streakStart: "Vyhľadaj slovo a začni sériu",
    weeklyTitle: "Tento týždeň",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týždenný cieľ splnený!",
    rankTitle: "Tvoja úroveň",
    toNext: (n) => (n === 1 ? "ešte 1 slovo do vyššej úrovne" : `ešte ${n} slov do vyššej úrovne`),
    topRank: "Najvyššia úroveň dosiahnutá!",
    collected: (n) => (n === 1 ? "1 slovo nazbierané" : `${n} slov nazbieraných`),
  },
  it: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 giorno di fila" : `${n} giorni di fila`),
    streakStart: "Cerca una parola per iniziare una serie",
    weeklyTitle: "Questa settimana",
    weeklyProgress: (n, goal) => `${n} / ${goal} parole nuove`,
    weeklyDone: "Obiettivo della settimana raggiunto!",
    rankTitle: "Il tuo grado",
    toNext: (n) => (n === 1 ? "ancora 1 parola per salire di livello" : `ancora ${n} parole per salire di livello`),
    topRank: "Grado massimo raggiunto!",
    collected: (n) => (n === 1 ? "1 parola raccolta" : `${n} parole raccolte`),
  },
  ja: {
    streakTitle: "連続",
    streakDays: (n) => `${n}日連続`,
    streakStart: "ことばを調べて連続記録をはじめよう",
    weeklyTitle: "今週",
    weeklyProgress: (n, goal) => `新しいことば ${n} / ${goal}`,
    weeklyDone: "今週の目標を達成！",
    rankTitle: "あなたのランク",
    toNext: (n) => `次のランクまであと ${n} ことば`,
    topRank: "最高ランクに到達！",
    collected: (n) => `${n} ことばを集めた`,
  },
  hi: {
    streakTitle: "लगातार",
    streakDays: (n) => (n === 1 ? "1 दिन लगातार" : `${n} दिन लगातार`),
    streakStart: "एक शब्द खोजें और सिलसिला शुरू करें",
    weeklyTitle: "इस हफ़्ते",
    weeklyProgress: (n, goal) => `${n} / ${goal} नए शब्द`,
    weeklyDone: "हफ़्ते का लक्ष्य पूरा!",
    rankTitle: "आपकी रैंक",
    toNext: (n) => (n === 1 ? "अगली रैंक के लिए 1 और शब्द" : `अगली रैंक के लिए ${n} और शब्द`),
    topRank: "सबसे ऊँची रैंक पर पहुँच गए!",
    collected: (n) => (n === 1 ? "1 शब्द जमा" : `${n} शब्द जमा`),
  },
  am: {
    streakTitle: "ተከታታይ",
    streakDays: (n) => (n === 1 ? "1 ቀን በተከታታይ" : `${n} ቀናት በተከታታይ`),
    streakStart: "ተከታታይ ለመጀመር ቃል ፈልግ",
    weeklyTitle: "በዚህ ሳምንት",
    weeklyProgress: (n, goal) => `${n} / ${goal} አዲስ ቃላት`,
    weeklyDone: "የሳምንቱ ግብ ተሳክቷል!",
    rankTitle: "ደረጃህ",
    toNext: (n) => (n === 1 ? "ወደ ቀጣዩ ደረጃ 1 ተጨማሪ ቃል" : `ወደ ቀጣዩ ደረጃ ${n} ተጨማሪ ቃላት`),
    topRank: "ከፍተኛውን ደረጃ ደርሰሃል!",
    collected: (n) => (n === 1 ? "1 ቃል ተሰብስቧል" : `${n} ቃላት ተሰብስበዋል`),
  },
  uk: {
    streakTitle: "Серія",
    streakDays: (n) => (n === 1 ? "1 день поспіль" : `${n} днів поспіль`),
    streakStart: "Знайди слово, щоб почати серію",
    weeklyTitle: "Цього тижня",
    weeklyProgress: (n, goal) => `${n} / ${goal} нових слів`,
    weeklyDone: "Ціль тижня виконано!",
    rankTitle: "Твій ранг",
    toNext: (n) => (n === 1 ? "ще 1 слово до нового рангу" : `ще ${n} слів до нового рангу`),
    topRank: "Досягнуто найвищий ранг!",
    collected: (n) => (n === 1 ? "1 слово зібрано" : `${n} слів зібрано`),
  },
  tr: {
    streakTitle: "Seri",
    streakDays: (n) => `üst üste ${n} gün`,
    streakStart: "Bir seri başlatmak için kelime ara",
    weeklyTitle: "Bu hafta",
    weeklyProgress: (n, goal) => `${n} / ${goal} yeni kelime`,
    weeklyDone: "Haftalık hedef tamam!",
    rankTitle: "Seviyen",
    toNext: (n) => `bir üst seviye için ${n} kelime daha`,
    topRank: "En yüksek seviyeye ulaştın!",
    collected: (n) => `${n} kelime toplandı`,
  },
  pl: {
    streakTitle: "Seria",
    streakDays: (n) => (n === 1 ? "1 dzień z rzędu" : `${n} dni z rzędu`),
    streakStart: "Wyszukaj słowo, aby zacząć serię",
    weeklyTitle: "W tym tygodniu",
    weeklyProgress: (n, goal) => `${n} / ${goal} nowych słów`,
    weeklyDone: "Cel tygodnia osiągnięty!",
    rankTitle: "Twoja ranga",
    toNext: (n) => (n === 1 ? "jeszcze 1 słowo do wyższej rangi" : `jeszcze ${n} słów do wyższej rangi`),
    topRank: "Osiągnięto najwyższą rangę!",
    collected: (n) => (n === 1 ? "1 słowo zebrane" : `${n} słów zebranych`),
  },
  fa: {
    streakTitle: "زنجیره",
    streakDays: (n) => (n === 1 ? "۱ روز پیاپی" : `${n} روز پیاپی`),
    streakStart: "برای شروع زنجیره یک واژه جست‌وجو کن",
    weeklyTitle: "این هفته",
    weeklyProgress: (n, goal) => `${n} / ${goal} واژه‌ی جدید`,
    weeklyDone: "هدف هفته کامل شد!",
    rankTitle: "رتبه‌ی تو",
    toNext: (n) => (n === 1 ? "۱ واژه‌ی دیگر تا رتبه‌ی بعدی" : `${n} واژه‌ی دیگر تا رتبه‌ی بعدی`),
    topRank: "به بالاترین رتبه رسیدی!",
    collected: (n) => (n === 1 ? "۱ واژه جمع شد" : `${n} واژه جمع شد`),
  },
  id: {
    streakTitle: "Beruntun",
    streakDays: (n) => `${n} hari beruntun`,
    streakStart: "Cari sebuah kata untuk memulai rentetan",
    weeklyTitle: "Minggu ini",
    weeklyProgress: (n, goal) => `${n} / ${goal} kata baru`,
    weeklyDone: "Target minggu ini tercapai!",
    rankTitle: "Peringkatmu",
    toNext: (n) => `${n} kata lagi untuk naik peringkat`,
    topRank: "Peringkat tertinggi tercapai!",
    collected: (n) => `${n} kata terkumpul`,
  },
  nl: {
    streakTitle: "Reeks",
    streakDays: (n) => (n === 1 ? "1 dag op rij" : `${n} dagen op rij`),
    streakStart: "Zoek een woord op om een reeks te starten",
    weeklyTitle: "Deze week",
    weeklyProgress: (n, goal) => `${n} / ${goal} nieuwe woorden`,
    weeklyDone: "Weekdoel gehaald!",
    rankTitle: "Jouw rang",
    toNext: (n) => (n === 1 ? "nog 1 woord tot de volgende rang" : `nog ${n} woorden tot de volgende rang`),
    topRank: "Hoogste rang bereikt!",
    collected: (n) => (n === 1 ? "1 woord verzameld" : `${n} woorden verzameld`),
  },
  el: {
    streakTitle: "Σερί",
    streakDays: (n) => (n === 1 ? "1 μέρα στη σειρά" : `${n} μέρες στη σειρά`),
    streakStart: "Ψάξε μια λέξη για να ξεκινήσεις σερί",
    weeklyTitle: "Αυτή την εβδομάδα",
    weeklyProgress: (n, goal) => `${n} / ${goal} νέες λέξεις`,
    weeklyDone: "Ο εβδομαδιαίος στόχος ολοκληρώθηκε!",
    rankTitle: "Η βαθμίδα σου",
    toNext: (n) => (n === 1 ? "1 λέξη ακόμα για την επόμενη βαθμίδα" : `${n} λέξεις ακόμα για την επόμενη βαθμίδα`),
    topRank: "Έφτασες στην ανώτατη βαθμίδα!",
    collected: (n) => (n === 1 ? "1 λέξη μαζεύτηκε" : `${n} λέξεις μαζεύτηκαν`),
  },
  zu: {
    streakTitle: "Ukulandelana",
    streakDays: (n) => (n === 1 ? "usuku olu-1 ngokulandelana" : `izinsuku ezi-${n} ngokulandelana`),
    streakStart: "Sesha igama ukuze uqale ukulandelana",
    weeklyTitle: "Kuleli sonto",
    weeklyProgress: (n, goal) => `${n} / ${goal} amagama amasha`,
    weeklyDone: "Umgomo weviki uphelele!",
    rankTitle: "Izinga lakho",
    toNext: (n) => (n === 1 ? "elilodwa igama ukuze ukhuphuke izinga" : `amagama angu-${n} ukuze ukhuphuke izinga`),
    topRank: "Ufinyelele izinga eliphezulu!",
    collected: (n) => (n === 1 ? "igama eli-1 liqoqiwe" : `amagama angu-${n} aqoqiwe`),
  },
};

export function gameCopy(lang: string): GameCopy {
  return GAME_COPY[lang] ?? GAME_COPY.en;
}
