import type { RankKey } from "./gamification";

/**
 * Localized copy for the kids gamification widgets, in all 30+ UI languages
 * (Gadi 2026-08-13: make the whole kids experience native everywhere, like
 * the rest of the app — it sits right next to "אוצר המילים שלי"). Kept out
 * of the pure gamification module so that stays i/o- and i18n-free. English
 * is the fallback for any code not listed. Never translates "Gadit".
 */

// Inner is Partial so a language may omit the newer long-tail tiers and fall
// back to English per-key (rankLabel below). English is the complete source
// and MUST carry every RankKey. New tiers are en+he now; other languages get
// the English label until a small translation pass fills them in.
export const RANK_LABELS: Record<string, Partial<Record<RankKey, string>>> = {
  en: { scout: "Word Scout", explorer: "Word Explorer", tracker: "Word Tracker", ranger: "Word Ranger", guide: "Word Guide", master: "Word Master", champion: "Word Champion", sage: "Word Sage", virtuoso: "Word Virtuoso", legend: "Word Legend", wizard: "Word Wizard", grandmaster: "Word Grandmaster" },
  he: { scout: "מגלה מתחיל", explorer: "מגלה מילים", tracker: "חוקר מילים", ranger: "מגלה מנוסה", guide: "מדריך מילים", master: "אלוף המילים", champion: "גיבור מילים", sage: "חכם המילים", virtuoso: "אמן המילים", legend: "אגדת המילים", wizard: "קוסם המילים", grandmaster: "קיסר המילים" },
  ar: { scout: "مستكشف مبتدئ", explorer: "مستكشف كلمات", tracker: "باحث كلمات", ranger: "مستكشف متمرّس", guide: "مرشد كلمات", master: "بطل الكلمات", champion: "نجم الكلمات", sage: "حكيم الكلمات", virtuoso: "فنان الكلمات", legend: "أسطورة الكلمات", wizard: "ساحر الكلمات", grandmaster: "إمبراطور الكلمات" },
  ru: { scout: "Юный искатель", explorer: "Искатель слов", tracker: "Следопыт слов", ranger: "Опытный искатель", guide: "Проводник слов", master: "Мастер слов", champion: "Чемпион слов", sage: "Мудрец слов", virtuoso: "Виртуоз слов", legend: "Легенда слов", wizard: "Волшебник слов", grandmaster: "Гроссмейстер слов" },
  es: { scout: "Explorador novato", explorer: "Explorador de palabras", tracker: "Rastreador de palabras", ranger: "Explorador experto", guide: "Guía de palabras", master: "Maestro de palabras", champion: "Campeón de palabras", sage: "Sabio de palabras", virtuoso: "Virtuoso de palabras", legend: "Leyenda de palabras", wizard: "Mago de palabras", grandmaster: "Gran maestro de palabras" },
  pt: { scout: "Explorador iniciante", explorer: "Explorador de palavras", tracker: "Rastreador de palavras", ranger: "Explorador experiente", guide: "Guia de palavras", master: "Mestre das palavras", champion: "Campeão das palavras", sage: "Sábio das palavras", virtuoso: "Virtuoso das palavras", legend: "Lenda das palavras", wizard: "Mago das palavras", grandmaster: "Grão-mestre das palavras" },
  fr: { scout: "Éclaireur des mots", explorer: "Explorateur de mots", tracker: "Traqueur de mots", ranger: "Explorateur chevronné", guide: "Guide des mots", master: "Maître des mots", champion: "Champion des mots", sage: "Sage des mots", virtuoso: "Virtuose des mots", legend: "Légende des mots", wizard: "Magicien des mots", grandmaster: "Grand maître des mots" },
  de: { scout: "Wort-Späher", explorer: "Wort-Entdecker", tracker: "Wort-Spurenleser", ranger: "Erfahrener Entdecker", guide: "Wort-Guide", master: "Wort-Meister", champion: "Wort-Champion", sage: "Wort-Weiser", virtuoso: "Wort-Virtuose", legend: "Wort-Legende", wizard: "Wort-Zauberer", grandmaster: "Wort-Großmeister" },
  cs: { scout: "Začínající objevitel", explorer: "Objevitel slov", tracker: "Stopař slov", ranger: "Zkušený objevitel", guide: "Průvodce slovy", master: "Mistr slov", champion: "Šampion slov", sage: "Mudrc slov", virtuoso: "Virtuos slov", legend: "Legenda slov", wizard: "Kouzelník slov", grandmaster: "Velmistr slov" },
  sk: { scout: "Začínajúci objaviteľ", explorer: "Objaviteľ slov", tracker: "Stopár slov", ranger: "Skúsený objaviteľ", guide: "Sprievodca slovami", master: "Majster slov", champion: "Šampión slov", sage: "Mudrc slov", virtuoso: "Virtuóz slov", legend: "Legenda slov", wizard: "Čarodejník slov", grandmaster: "Veľmajster slov" },
  it: { scout: "Esploratore alle prime armi", explorer: "Esploratore di parole", tracker: "Cercatore di parole", ranger: "Esploratore esperto", guide: "Guida delle parole", master: "Maestro delle parole", champion: "Campione delle parole", sage: "Saggio delle parole", virtuoso: "Virtuoso delle parole", legend: "Leggenda delle parole", wizard: "Mago delle parole", grandmaster: "Gran maestro delle parole" },
  ja: { scout: "ことばの見習い", explorer: "ことばの探検家", tracker: "ことばの追跡者", ranger: "ベテラン探検家", guide: "ことばの案内人", master: "ことばの達人", champion: "ことばの王者", sage: "ことばの賢者", virtuoso: "ことばの巨匠", legend: "ことばの伝説", wizard: "ことばの魔法使い", grandmaster: "ことばの覇王" },
  hi: { scout: "नौसिखिया खोजी", explorer: "शब्द खोजी", tracker: "शब्द अन्वेषक", ranger: "अनुभवी खोजी", guide: "शब्द मार्गदर्शक", master: "शब्द माहिर", champion: "शब्द चैंपियन", sage: "शब्द ऋषि", virtuoso: "शब्द उस्ताद", legend: "शब्द दिग्गज", wizard: "शब्द जादूगर", grandmaster: "शब्द महागुरु" },
  am: { scout: "ጀማሪ አሳሽ", explorer: "የቃላት አሳሽ", tracker: "የቃላት መርማሪ", ranger: "የተካነ አሳሽ", guide: "የቃላት መሪ", master: "የቃላት ጌታ", champion: "የቃላት አሸናፊ", sage: "የቃላት ጠቢብ", virtuoso: "የቃላት ሊቅ", legend: "የቃላት አፈ ታሪክ", wizard: "የቃላት ጠንቋይ", grandmaster: "የቃላት ንጉሥ" },
  uk: { scout: "Юний шукач", explorer: "Шукач слів", tracker: "Слідопит слів", ranger: "Досвідчений шукач", guide: "Провідник слів", master: "Майстер слів", champion: "Чемпіон слів", sage: "Мудрець слів", virtuoso: "Віртуоз слів", legend: "Легенда слів", wizard: "Чарівник слів", grandmaster: "Гросмейстер слів" },
  tr: { scout: "Acemi kâşif", explorer: "Kelime kâşifi", tracker: "Kelime izcisi", ranger: "Deneyimli kâşif", guide: "Kelime rehberi", master: "Kelime ustası", champion: "Kelime şampiyonu", sage: "Kelime bilgesi", virtuoso: "Kelime virtüözü", legend: "Kelime efsanesi", wizard: "Kelime büyücüsü", grandmaster: "Kelime büyük ustası" },
  pl: { scout: "Początkujący odkrywca", explorer: "Odkrywca słów", tracker: "Tropiciel słów", ranger: "Doświadczony odkrywca", guide: "Przewodnik po słowach", master: "Mistrz słów", champion: "Czempion słów", sage: "Mędrzec słów", virtuoso: "Wirtuoz słów", legend: "Legenda słów", wizard: "Czarodziej słów", grandmaster: "Arcymistrz słów" },
  fa: { scout: "کاوشگر تازه‌کار", explorer: "کاوشگر واژه‌ها", tracker: "ردیاب واژه‌ها", ranger: "کاوشگر باتجربه", guide: "راهنمای واژه‌ها", master: "استاد واژه‌ها", champion: "قهرمان واژه‌ها", sage: "فرزانهٔ واژه‌ها", virtuoso: "نابغهٔ واژه‌ها", legend: "اسطورهٔ واژه‌ها", wizard: "جادوگر واژه‌ها", grandmaster: "استاد اعظم واژه‌ها" },
  id: { scout: "Penjelajah pemula", explorer: "Penjelajah kata", tracker: "Pelacak kata", ranger: "Penjelajah berpengalaman", guide: "Pemandu kata", master: "Ahli kata", champion: "Juara kata", sage: "Pujangga kata", virtuoso: "Maestro kata", legend: "Legenda kata", wizard: "Penyihir kata", grandmaster: "Mahaguru kata" },
  nl: { scout: "Beginnende verkenner", explorer: "Woordverkenner", tracker: "Woordspeurder", ranger: "Ervaren verkenner", guide: "Woordgids", master: "Woordmeester", champion: "Woordkampioen", sage: "Woordwijze", virtuoso: "Woordvirtuoos", legend: "Woordlegende", wizard: "Woordtovenaar", grandmaster: "Woordgrootmeester" },
  el: { scout: "Αρχάριος εξερευνητής", explorer: "Εξερευνητής λέξεων", tracker: "Ιχνηλάτης λέξεων", ranger: "Έμπειρος εξερευνητής", guide: "Οδηγός λέξεων", master: "Δεξιοτέχνης λέξεων", champion: "Πρωταθλητής λέξεων", sage: "Σοφός λέξεων", virtuoso: "Βιρτουόζος λέξεων", legend: "Θρύλος λέξεων", wizard: "Μάγος λέξεων", grandmaster: "Αρχιμάστορας λέξεων" },
  zu: { scout: "Umhloli oqalayo", explorer: "Umhloli wamagama", tracker: "Umlandeli wamagama", ranger: "Umhloli onolwazi", guide: "Umholi wamagama", master: "Ingcweti yamagama", champion: "Iqhawe lamagama", sage: "Isihlakaniphi samagama", virtuoso: "Ingcithabuchopho yamagama", legend: "Inganekwane yamagama", wizard: "Usomlingo wamagama", grandmaster: "Inkosi yamagama" },
};

export function rankLabel(key: RankKey, lang: string): string {
  // Per-key fallback to English: a language that predates the long-tail tiers
  // still resolves them (RANK_LABELS.en is complete for every RankKey).
  return RANK_LABELS[lang]?.[key] ?? RANK_LABELS.en[key] ?? key;
}

export type GameCopy = {
  streakTitle: string;
  streakDays: (n: number) => string;
  streakStart: string;
  weeklyTitle: string;
  weeklyProgress: (n: number, goal: number) => string;
  weeklyDone: string;
  rankTitle: string;
  toNext: (n: number) => string;
  topRank: string;
  collected: (n: number) => string;
};

export const GAME_COPY: Record<string, GameCopy> = {
  en: {
    streakTitle: "Day streak",
    streakDays: (n) => (n === 1 ? "1 day in a row" : `${n} days in a row`),
    streakStart: "Look up a word to start a streak",
    weeklyTitle: "Weekly goal",
    weeklyProgress: (n, goal) => `${n} / ${goal} new words`,
    weeklyDone: "Goal complete!",
    rankTitle: "Your rank",
    toNext: (n) => (n === 1 ? "1 more point to level up" : `${n} more points to level up`),
    topRank: "Top rank reached!",
    collected: (n) => (n === 1 ? "1 word collected" : `${n} words collected`),
  },
  he: {
    streakTitle: "רצף ימים",
    streakDays: (n) => (n === 1 ? "יום אחד ברצף" : `${n} ימים ברצף`),
    streakStart: "חפשו מילה כדי להתחיל רצף",
    weeklyTitle: "יעד שבועי",
    weeklyProgress: (n, goal) => `${n} / ${goal} מילים חדשות`,
    weeklyDone: "היעד הושלם!",
    rankTitle: "הדרגה שלך",
    toNext: (n) => (n === 1 ? "עוד נקודה אחת לדרגה הבאה" : `עוד ${n} נקודות לדרגה הבאה`),
    topRank: "הגעת לדרגה הגבוהה ביותר!",
    collected: (n) => (n === 1 ? "מילה אחת באוצר" : `${n} מילים באוצר`),
  },
  ar: {
    streakTitle: "سلسلة",
    streakDays: (n) => (n === 1 ? "يوم واحد متتالٍ" : `${n} أيام متتالية`),
    streakStart: "ابحث عن كلمة لتبدأ سلسلة",
    weeklyTitle: "هذا الأسبوع",
    weeklyProgress: (n, goal) => `${n} / ${goal} كلمات جديدة`,
    weeklyDone: "أكملت هدف الأسبوع!",
    rankTitle: "رتبتك",
    toNext: (n) => (n === 1 ? "نقطة واحدة للترقية" : `${n} نقاط للترقية`),
    topRank: "وصلت إلى أعلى رتبة!",
    collected: (n) => (n === 1 ? "كلمة واحدة في المجموعة" : `${n} كلمات في المجموعة`),
  },
  ru: {
    streakTitle: "Серия",
    streakDays: (n) => (n === 1 ? "1 день подряд" : `${n} дней подряд`),
    streakStart: "Найди слово, чтобы начать серию",
    weeklyTitle: "На этой неделе",
    weeklyProgress: (n, goal) => `${n} / ${goal} новых слов`,
    weeklyDone: "Цель недели выполнена!",
    rankTitle: "Твой ранг",
    toNext: (n) => (n === 1 ? "ещё 1 очко до нового ранга" : `ещё ${n} очк(а/ов) до нового ранга`),
    topRank: "Достигнут высший ранг!",
    collected: (n) => (n === 1 ? "1 слово собрано" : `${n} слов собрано`),
  },
  es: {
    streakTitle: "Racha",
    streakDays: (n) => (n === 1 ? "1 día seguido" : `${n} días seguidos`),
    streakStart: "Busca una palabra para empezar una racha",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palabras nuevas`,
    weeklyDone: "¡Meta de la semana cumplida!",
    rankTitle: "Tu rango",
    toNext: (n) => (n === 1 ? "1 punto más para subir de nivel" : `${n} puntos más para subir de nivel`),
    topRank: "¡Rango máximo alcanzado!",
    collected: (n) => (n === 1 ? "1 palabra reunida" : `${n} palabras reunidas`),
  },
  pt: {
    streakTitle: "Sequência",
    streakDays: (n) => (n === 1 ? "1 dia seguido" : `${n} dias seguidos`),
    streakStart: "Busque uma palavra para começar uma sequência",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palavras novas`,
    weeklyDone: "Meta da semana concluída!",
    rankTitle: "Seu nível",
    toNext: (n) => (n === 1 ? "mais 1 ponto para subir de nível" : `mais ${n} pontos para subir de nível`),
    topRank: "Nível máximo alcançado!",
    collected: (n) => (n === 1 ? "1 palavra reunida" : `${n} palavras reunidas`),
  },
  fr: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 jour d'affilée" : `${n} jours d'affilée`),
    streakStart: "Cherche un mot pour lancer une série",
    weeklyTitle: "Cette semaine",
    weeklyProgress: (n, goal) => `${n} / ${goal} nouveaux mots`,
    weeklyDone: "Objectif de la semaine atteint !",
    rankTitle: "Ton rang",
    toNext: (n) => (n === 1 ? "encore 1 point pour monter de niveau" : `encore ${n} points pour monter de niveau`),
    topRank: "Rang maximal atteint !",
    collected: (n) => (n === 1 ? "1 mot collecté" : `${n} mots collectés`),
  },
  de: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 Tag in Folge" : `${n} Tage in Folge`),
    streakStart: "Schlag ein Wort nach, um eine Serie zu starten",
    weeklyTitle: "Diese Woche",
    weeklyProgress: (n, goal) => `${n} / ${goal} neue Wörter`,
    weeklyDone: "Wochenziel geschafft!",
    rankTitle: "Dein Rang",
    toNext: (n) => (n === 1 ? "noch 1 Punkt bis zum nächsten Rang" : `noch ${n} Punkte bis zum nächsten Rang`),
    topRank: "Höchster Rang erreicht!",
    collected: (n) => (n === 1 ? "1 Wort gesammelt" : `${n} Wörter gesammelt`),
  },
  cs: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 den v řadě" : `${n} dní v řadě`),
    streakStart: "Vyhledej slovo a začni sérii",
    weeklyTitle: "Tento týden",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týdenní cíl splněn!",
    rankTitle: "Tvoje úroveň",
    toNext: (n) => (n === 1 ? "ještě 1 bod do vyšší úrovně" : `ještě ${n} bodů do vyšší úrovně`),
    topRank: "Nejvyšší úroveň dosažena!",
    collected: (n) => (n === 1 ? "1 slovo nasbíráno" : `${n} slov nasbíráno`),
  },
  sk: {
    streakTitle: "Séria",
    streakDays: (n) => (n === 1 ? "1 deň v rade" : `${n} dní v rade`),
    streakStart: "Vyhľadaj slovo a začni sériu",
    weeklyTitle: "Tento týždeň",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týždenný cieľ splnený!",
    rankTitle: "Tvoja úroveň",
    toNext: (n) => (n === 1 ? "ešte 1 bod do vyššej úrovne" : `ešte ${n} bodov do vyššej úrovne`),
    topRank: "Najvyššia úroveň dosiahnutá!",
    collected: (n) => (n === 1 ? "1 slovo nazbierané" : `${n} slov nazbieraných`),
  },
  it: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 giorno di fila" : `${n} giorni di fila`),
    streakStart: "Cerca una parola per iniziare una serie",
    weeklyTitle: "Questa settimana",
    weeklyProgress: (n, goal) => `${n} / ${goal} parole nuove`,
    weeklyDone: "Obiettivo della settimana raggiunto!",
    rankTitle: "Il tuo grado",
    toNext: (n) => (n === 1 ? "ancora 1 punto per salire di livello" : `ancora ${n} punti per salire di livello`),
    topRank: "Grado massimo raggiunto!",
    collected: (n) => (n === 1 ? "1 parola raccolta" : `${n} parole raccolte`),
  },
  ja: {
    streakTitle: "連続",
    streakDays: (n) => `${n}日連続`,
    streakStart: "ことばを調べて連続記録をはじめよう",
    weeklyTitle: "今週",
    weeklyProgress: (n, goal) => `新しいことば ${n} / ${goal}`,
    weeklyDone: "今週の目標を達成！",
    rankTitle: "あなたのランク",
    toNext: (n) => `次のランクまであと ${n} ポイント`,
    topRank: "最高ランクに到達！",
    collected: (n) => `${n} ことばを集めた`,
  },
  hi: {
    streakTitle: "लगातार",
    streakDays: (n) => (n === 1 ? "1 दिन लगातार" : `${n} दिन लगातार`),
    streakStart: "एक शब्द खोजें और सिलसिला शुरू करें",
    weeklyTitle: "इस हफ़्ते",
    weeklyProgress: (n, goal) => `${n} / ${goal} नए शब्द`,
    weeklyDone: "हफ़्ते का लक्ष्य पूरा!",
    rankTitle: "आपकी रैंक",
    toNext: (n) => (n === 1 ? "अगली रैंक के लिए 1 और अंक" : `अगली रैंक के लिए ${n} और अंक`),
    topRank: "सबसे ऊँची रैंक पर पहुँच गए!",
    collected: (n) => (n === 1 ? "1 शब्द जमा" : `${n} शब्द जमा`),
  },
  am: {
    streakTitle: "ተከታታይ",
    streakDays: (n) => (n === 1 ? "1 ቀን በተከታታይ" : `${n} ቀናት በተከታታይ`),
    streakStart: "ተከታታይ ለመጀመር ቃል ፈልግ",
    weeklyTitle: "በዚህ ሳምንት",
    weeklyProgress: (n, goal) => `${n} / ${goal} አዲስ ቃላት`,
    weeklyDone: "የሳምንቱ ግብ ተሳክቷል!",
    rankTitle: "ደረጃህ",
    toNext: (n) => (n === 1 ? "ወደ ቀጣዩ ደረጃ 1 ተጨማሪ ነጥብ" : `ወደ ቀጣዩ ደረጃ ${n} ተጨማሪ ነጥቦች`),
    topRank: "ከፍተኛውን ደረጃ ደርሰሃል!",
    collected: (n) => (n === 1 ? "1 ቃል ተሰብስቧል" : `${n} ቃላት ተሰብስበዋል`),
  },
  uk: {
    streakTitle: "Серія",
    streakDays: (n) => (n === 1 ? "1 день поспіль" : `${n} днів поспіль`),
    streakStart: "Знайди слово, щоб почати серію",
    weeklyTitle: "Цього тижня",
    weeklyProgress: (n, goal) => `${n} / ${goal} нових слів`,
    weeklyDone: "Ціль тижня виконано!",
    rankTitle: "Твій ранг",
    toNext: (n) => (n === 1 ? "ще 1 бал до нового рангу" : `ще ${n} балів до нового рангу`),
    topRank: "Досягнуто найвищий ранг!",
    collected: (n) => (n === 1 ? "1 слово зібрано" : `${n} слів зібрано`),
  },
  tr: {
    streakTitle: "Seri",
    streakDays: (n) => `üst üste ${n} gün`,
    streakStart: "Bir seri başlatmak için kelime ara",
    weeklyTitle: "Bu hafta",
    weeklyProgress: (n, goal) => `${n} / ${goal} yeni kelime`,
    weeklyDone: "Haftalık hedef tamam!",
    rankTitle: "Seviyen",
    toNext: (n) => `bir üst seviye için ${n} puan daha`,
    topRank: "En yüksek seviyeye ulaştın!",
    collected: (n) => `${n} kelime toplandı`,
  },
  pl: {
    streakTitle: "Seria",
    streakDays: (n) => (n === 1 ? "1 dzień z rzędu" : `${n} dni z rzędu`),
    streakStart: "Wyszukaj słowo, aby zacząć serię",
    weeklyTitle: "W tym tygodniu",
    weeklyProgress: (n, goal) => `${n} / ${goal} nowych słów`,
    weeklyDone: "Cel tygodnia osiągnięty!",
    rankTitle: "Twoja ranga",
    toNext: (n) => (n === 1 ? "jeszcze 1 punkt do wyższej rangi" : `jeszcze ${n} punktów do wyższej rangi`),
    topRank: "Osiągnięto najwyższą rangę!",
    collected: (n) => (n === 1 ? "1 słowo zebrane" : `${n} słów zebranych`),
  },
  fa: {
    streakTitle: "زنجیره",
    streakDays: (n) => (n === 1 ? "۱ روز پیاپی" : `${n} روز پیاپی`),
    streakStart: "برای شروع زنجیره یک واژه جست‌وجو کن",
    weeklyTitle: "این هفته",
    weeklyProgress: (n, goal) => `${n} / ${goal} واژه‌ی جدید`,
    weeklyDone: "هدف هفته کامل شد!",
    rankTitle: "رتبه‌ی تو",
    toNext: (n) => (n === 1 ? "۱ امتیاز دیگر تا رتبه‌ی بعدی" : `${n} امتیاز دیگر تا رتبه‌ی بعدی`),
    topRank: "به بالاترین رتبه رسیدی!",
    collected: (n) => (n === 1 ? "۱ واژه جمع شد" : `${n} واژه جمع شد`),
  },
  id: {
    streakTitle: "Beruntun",
    streakDays: (n) => `${n} hari beruntun`,
    streakStart: "Cari sebuah kata untuk memulai rentetan",
    weeklyTitle: "Minggu ini",
    weeklyProgress: (n, goal) => `${n} / ${goal} kata baru`,
    weeklyDone: "Target minggu ini tercapai!",
    rankTitle: "Peringkatmu",
    toNext: (n) => `${n} poin lagi untuk naik peringkat`,
    topRank: "Peringkat tertinggi tercapai!",
    collected: (n) => `${n} kata terkumpul`,
  },
  nl: {
    streakTitle: "Reeks",
    streakDays: (n) => (n === 1 ? "1 dag op rij" : `${n} dagen op rij`),
    streakStart: "Zoek een woord op om een reeks te starten",
    weeklyTitle: "Deze week",
    weeklyProgress: (n, goal) => `${n} / ${goal} nieuwe woorden`,
    weeklyDone: "Weekdoel gehaald!",
    rankTitle: "Jouw rang",
    toNext: (n) => (n === 1 ? "nog 1 punt tot de volgende rang" : `nog ${n} punten tot de volgende rang`),
    topRank: "Hoogste rang bereikt!",
    collected: (n) => (n === 1 ? "1 woord verzameld" : `${n} woorden verzameld`),
  },
  el: {
    streakTitle: "Σερί",
    streakDays: (n) => (n === 1 ? "1 μέρα στη σειρά" : `${n} μέρες στη σειρά`),
    streakStart: "Ψάξε μια λέξη για να ξεκινήσεις σερί",
    weeklyTitle: "Αυτή την εβδομάδα",
    weeklyProgress: (n, goal) => `${n} / ${goal} νέες λέξεις`,
    weeklyDone: "Ο εβδομαδιαίος στόχος ολοκληρώθηκε!",
    rankTitle: "Η βαθμίδα σου",
    toNext: (n) => (n === 1 ? "1 πόντος ακόμα για την επόμενη βαθμίδα" : `${n} πόντοι ακόμα για την επόμενη βαθμίδα`),
    topRank: "Έφτασες στην ανώτατη βαθμίδα!",
    collected: (n) => (n === 1 ? "1 λέξη μαζεύτηκε" : `${n} λέξεις μαζεύτηκαν`),
  },
  zu: {
    streakTitle: "Ukulandelana",
    streakDays: (n) => (n === 1 ? "usuku olu-1 ngokulandelana" : `izinsuku ezi-${n} ngokulandelana`),
    streakStart: "Sesha igama ukuze uqale ukulandelana",
    weeklyTitle: "Kuleli sonto",
    weeklyProgress: (n, goal) => `${n} / ${goal} amagama amasha`,
    weeklyDone: "Umgomo weviki uphelele!",
    rankTitle: "Izinga lakho",
    toNext: (n) => (n === 1 ? "iphuzu elilodwa ukuze ukhuphuke izinga" : `amaphuzu angu-${n} ukuze ukhuphuke izinga`),
    topRank: "Ufinyelele izinga eliphezulu!",
    collected: (n) => (n === 1 ? "igama eli-1 liqoqiwe" : `amagama angu-${n} aqoqiwe`),
  },
};

export function gameCopy(lang: string): GameCopy {
  return GAME_COPY[lang] ?? GAME_COPY.en;
}
