import type { RankKey } from "./gamification";

/**
 * Localized copy for the kids gamification widgets, in all 30+ UI languages
 * (Gadi 2026-08-13: make the whole kids experience native everywhere, like
 * the rest of the app — it sits right next to "אוצר המילים שלי"). Kept out
 * of the pure gamification module so that stays i/o- and i18n-free. English
 * is the fallback for any code not listed. Never translates "Gadit".
 */

// Inner is Partial so a language may omit the newer long-tail tiers and fall
// back to English per-key (rankLabel below). English is the complete source
// and MUST carry every RankKey. New tiers are en+he now; other languages get
// the English label until a small translation pass fills them in.
export const RANK_LABELS: Record<string, Partial<Record<RankKey, string>>> = {
  en: { scout: "Word Scout", explorer: "Word Explorer", tracker: "Word Tracker", ranger: "Word Ranger", guide: "Word Guide", master: "Word Master", champion: "Word Champion", sage: "Word Sage", virtuoso: "Word Virtuoso", legend: "Word Legend", wizard: "Word Wizard", grandmaster: "Word Grandmaster" },
  he: { scout: "מגלה מתחיל", explorer: "מגלה מילים", tracker: "חוקר מילים", ranger: "מגלה מנוסה", guide: "מדריך מילים", master: "אלוף המילים", champion: "גיבור מילים", sage: "חכם המילים", virtuoso: "אמן המילים", legend: "אגדת המילים", wizard: "קוסם המילים", grandmaster: "קיסר המילים" },
  ar: { scout: "مستكشف مبتدئ", explorer: "مستكشف كلمات", tracker: "باحث كلمات", ranger: "مستكشف متمرّس", guide: "مرشد كلمات", master: "بطل الكلمات", champion: "نجم الكلمات", sage: "حكيم الكلمات", virtuoso: "فنان الكلمات", legend: "أسطورة الكلمات", wizard: "ساحر الكلمات", grandmaster: "إمبراطور الكلمات" },
  ru: { scout: "Юный искатель", explorer: "Искатель слов", tracker: "Следопыт слов", ranger: "Опытный искатель", guide: "Проводник слов", master: "Мастер слов", champion: "Чемпион слов", sage: "Мудрец слов", virtuoso: "Виртуоз слов", legend: "Легенда слов", wizard: "Волшебник слов", grandmaster: "Гроссмейстер слов" },
  es: { scout: "Explorador novato", explorer: "Explorador de palabras", tracker: "Rastreador de palabras", ranger: "Explorador experto", guide: "Guía de palabras", master: "Maestro de palabras", champion: "Campeón de palabras", sage: "Sabio de palabras", virtuoso: "Virtuoso de palabras", legend: "Leyenda de palabras", wizard: "Mago de palabras", grandmaster: "Gran maestro de palabras" },
  pt: { scout: "Explorador iniciante", explorer: "Explorador de palavras", tracker: "Rastreador de palavras", ranger: "Explorador experiente", guide: "Guia de palavras", master: "Mestre das palavras", champion: "Campeão das palavras", sage: "Sábio das palavras", virtuoso: "Virtuoso das palavras", legend: "Lenda das palavras", wizard: "Mago das palavras", grandmaster: "Grão-mestre das palavras" },
  fr: { scout: "Éclaireur des mots", explorer: "Explorateur de mots", tracker: "Traqueur de mots", ranger: "Explorateur chevronné", guide: "Guide des mots", master: "Maître des mots", champion: "Champion des mots", sage: "Sage des mots", virtuoso: "Virtuose des mots", legend: "Légende des mots", wizard: "Magicien des mots", grandmaster: "Grand maître des mots" },
  de: { scout: "Wort-Späher", explorer: "Wort-Entdecker", tracker: "Wort-Spurenleser", ranger: "Erfahrener Entdecker", guide: "Wort-Guide", master: "Wort-Meister", champion: "Wort-Champion", sage: "Wort-Weiser", virtuoso: "Wort-Virtuose", legend: "Wort-Legende", wizard: "Wort-Zauberer", grandmaster: "Wort-Großmeister" },
  cs: { scout: "Začínající objevitel", explorer: "Objevitel slov", tracker: "Stopař slov", ranger: "Zkušený objevitel", guide: "Průvodce slovy", master: "Mistr slov", champion: "Šampion slov", sage: "Mudrc slov", virtuoso: "Virtuos slov", legend: "Legenda slov", wizard: "Kouzelník slov", grandmaster: "Velmistr slov" },
  sk: { scout: "Začínajúci objaviteľ", explorer: "Objaviteľ slov", tracker: "Stopár slov", ranger: "Skúsený objaviteľ", guide: "Sprievodca slovami", master: "Majster slov", champion: "Šampión slov", sage: "Mudrc slov", virtuoso: "Virtuóz slov", legend: "Legenda slov", wizard: "Čarodejník slov", grandmaster: "Veľmajster slov" },
  it: { scout: "Esploratore alle prime armi", explorer: "Esploratore di parole", tracker: "Cercatore di parole", ranger: "Esploratore esperto", guide: "Guida delle parole", master: "Maestro delle parole", champion: "Campione delle parole", sage: "Saggio delle parole", virtuoso: "Virtuoso delle parole", legend: "Leggenda delle parole", wizard: "Mago delle parole", grandmaster: "Gran maestro delle parole" },
  ja: { scout: "ことばの見習い", explorer: "ことばの探検家", tracker: "ことばの追跡者", ranger: "ベテラン探検家", guide: "ことばの案内人", master: "ことばの達人", champion: "ことばの王者", sage: "ことばの賢者", virtuoso: "ことばの巨匠", legend: "ことばの伝説", wizard: "ことばの魔法使い", grandmaster: "ことばの覇王" },
  hi: { scout: "नौसिखिया खोजी", explorer: "शब्द खोजी", tracker: "शब्द अन्वेषक", ranger: "अनुभवी खोजी", guide: "शब्द मार्गदर्शक", master: "शब्द माहिर", champion: "शब्द चैंपियन", sage: "शब्द ऋषि", virtuoso: "शब्द उस्ताद", legend: "शब्द दिग्गज", wizard: "शब्द जादूगर", grandmaster: "शब्द महागुरु" },
  am: { scout: "ጀማሪ አሳሽ", explorer: "የቃላት አሳሽ", tracker: "የቃላት መርማሪ", ranger: "የተካነ አሳሽ", guide: "የቃላት መሪ", master: "የቃላት ጌታ", champion: "የቃላት አሸናፊ", sage: "የቃላት ጠቢብ", virtuoso: "የቃላት ሊቅ", legend: "የቃላት አፈ ታሪክ", wizard: "የቃላት ጠንቋይ", grandmaster: "የቃላት ንጉሥ" },
  uk: { scout: "Юний шукач", explorer: "Шукач слів", tracker: "Слідопит слів", ranger: "Досвідчений шукач", guide: "Провідник слів", master: "Майстер слів", champion: "Чемпіон слів", sage: "Мудрець слів", virtuoso: "Віртуоз слів", legend: "Легенда слів", wizard: "Чарівник слів", grandmaster: "Гросмейстер слів" },
  tr: { scout: "Acemi kâşif", explorer: "Kelime kâşifi", tracker: "Kelime izcisi", ranger: "Deneyimli kâşif", guide: "Kelime rehberi", master: "Kelime ustası", champion: "Kelime şampiyonu", sage: "Kelime bilgesi", virtuoso: "Kelime virtüözü", legend: "Kelime efsanesi", wizard: "Kelime büyücüsü", grandmaster: "Kelime büyük ustası" },
  pl: { scout: "Początkujący odkrywca", explorer: "Odkrywca słów", tracker: "Tropiciel słów", ranger: "Doświadczony odkrywca", guide: "Przewodnik po słowach", master: "Mistrz słów", champion: "Czempion słów", sage: "Mędrzec słów", virtuoso: "Wirtuoz słów", legend: "Legenda słów", wizard: "Czarodziej słów", grandmaster: "Arcymistrz słów" },
  fa: { scout: "کاوشگر تازه‌کار", explorer: "کاوشگر واژه‌ها", tracker: "ردیاب واژه‌ها", ranger: "کاوشگر باتجربه", guide: "راهنمای واژه‌ها", master: "استاد واژه‌ها", champion: "قهرمان واژه‌ها", sage: "فرزانهٔ واژه‌ها", virtuoso: "نابغهٔ واژه‌ها", legend: "اسطورهٔ واژه‌ها", wizard: "جادوگر واژه‌ها", grandmaster: "استاد اعظم واژه‌ها" },
  id: { scout: "Penjelajah pemula", explorer: "Penjelajah kata", tracker: "Pelacak kata", ranger: "Penjelajah berpengalaman", guide: "Pemandu kata", master: "Ahli kata", champion: "Juara kata", sage: "Pujangga kata", virtuoso: "Maestro kata", legend: "Legenda kata", wizard: "Penyihir kata", grandmaster: "Mahaguru kata" },
  nl: { scout: "Beginnende verkenner", explorer: "Woordverkenner", tracker: "Woordspeurder", ranger: "Ervaren verkenner", guide: "Woordgids", master: "Woordmeester", champion: "Woordkampioen", sage: "Woordwijze", virtuoso: "Woordvirtuoos", legend: "Woordlegende", wizard: "Woordtovenaar", grandmaster: "Woordgrootmeester" },
  el: { scout: "Αρχάριος εξερευνητής", explorer: "Εξερευνητής λέξεων", tracker: "Ιχνηλάτης λέξεων", ranger: "Έμπειρος εξερευνητής", guide: "Οδηγός λέξεων", master: "Δεξιοτέχνης λέξεων", champion: "Πρωταθλητής λέξεων", sage: "Σοφός λέξεων", virtuoso: "Βιρτουόζος λέξεων", legend: "Θρύλος λέξεων", wizard: "Μάγος λέξεων", grandmaster: "Αρχιμάστορας λέξεων" },
  zu: { scout: "Umhloli oqalayo", explorer: "Umhloli wamagama", tracker: "Umlandeli wamagama", ranger: "Umhloli onolwazi", guide: "Umholi wamagama", master: "Ingcweti yamagama", champion: "Iqhawe lamagama", sage: "Isihlakaniphi samagama", virtuoso: "Ingcithabuchopho yamagama", legend: "Inganekwane yamagama", wizard: "Usomlingo wamagama", grandmaster: "Inkosi yamagama" },
};

// 11 store-locale languages (added 2026-08-22): full 12-tier rank titles.
Object.assign(RANK_LABELS, {
  "af": {"scout":"Woordverkenner","explorer":"Woordontdekker","tracker":"Woordspoorsnyer","ranger":"Woordwagter","guide":"Woordgids","master":"Woordmeester","champion":"Woordkampioen","sage":"Woordwyse","virtuoso":"Woordvirtuoos","legend":"Woordlegende","wizard":"Woordtowenaar","grandmaster":"Woordgrootmeester"},
  "bn": {"scout":"শব্দ স্কাউট","explorer":"শব্দ অভিযাত্রী","tracker":"শব্দ সন্ধানী","ranger":"শব্দ রক্ষী","guide":"শব্দ পথপ্রদর্শক","master":"শব্দ মাস্টার","champion":"শব্দ চ্যাম্পিয়ন","sage":"শব্দ ঋষি","virtuoso":"শব্দ নিপুণ","legend":"শব্দ কিংবদন্তি","wizard":"শব্দ জাদুকর","grandmaster":"শব্দ মহাগুরু"},
  "da": {"scout":"Ordspejder","explorer":"Ordopdager","tracker":"Ordsporer","ranger":"Ordvogter","guide":"Ordguide","master":"Ordmester","champion":"Ordchampion","sage":"Ordvismand","virtuoso":"Ordvirtuos","legend":"Ordlegende","wizard":"Ordtroldmand","grandmaster":"Ordstormester"},
  "fil": {"scout":"Iskaut ng Salita","explorer":"Eksplorador ng Salita","tracker":"Tagasubaybay ng Salita","ranger":"Bantay ng Salita","guide":"Gabay ng Salita","master":"Master ng Salita","champion":"Kampeon ng Salita","sage":"Pantas ng Salita","virtuoso":"Birtuoso ng Salita","legend":"Alamat ng Salita","wizard":"Salamangkero ng Salita","grandmaster":"Grandmaster ng Salita"},
  "hu": {"scout":"Szófelderítő","explorer":"Szófelfedező","tracker":"Szónyomkövető","ranger":"Szóőr","guide":"Szóvezető","master":"Szómester","champion":"Szóbajnok","sage":"Szóbölcs","virtuoso":"Szóvirtuóz","legend":"Szólegenda","wizard":"Szóvarázsló","grandmaster":"Szónagymester"},
  "ko": {"scout":"단어 스카우트","explorer":"단어 탐험가","tracker":"단어 추적자","ranger":"단어 레인저","guide":"단어 안내자","master":"단어 마스터","champion":"단어 챔피언","sage":"단어 현자","virtuoso":"단어 명인","legend":"단어 전설","wizard":"단어 마법사","grandmaster":"단어 그랜드마스터"},
  "sw": {"scout":"Skauti wa Neno","explorer":"Mgunduzi wa Neno","tracker":"Mfuatiliaji wa Neno","ranger":"Mlinzi wa Neno","guide":"Kiongozi wa Neno","master":"Bwana wa Neno","champion":"Bingwa wa Neno","sage":"Mjuzi wa Neno","virtuoso":"Gwiji wa Neno","legend":"Hekaya wa Neno","wizard":"Mchawi wa Neno","grandmaster":"Bingwa Mkuu wa Neno"},
  "th": {"scout":"ลูกเสือคำศัพท์","explorer":"นักสำรวจคำศัพท์","tracker":"นักติดตามคำศัพท์","ranger":"ผู้พิทักษ์คำศัพท์","guide":"ผู้นำทางคำศัพท์","master":"มาสเตอร์คำศัพท์","champion":"แชมป์คำศัพท์","sage":"ปราชญ์คำศัพท์","virtuoso":"ผู้เชี่ยวชาญคำศัพท์","legend":"ตำนานคำศัพท์","wizard":"พ่อมดคำศัพท์","grandmaster":"ปรมาจารย์คำศัพท์"},
  "vi": {"scout":"Trinh Sát Từ","explorer":"Nhà Thám Hiểm Từ","tracker":"Người Truy Vết Từ","ranger":"Vệ Binh Từ","guide":"Người Dẫn Đường Từ","master":"Bậc Thầy Từ","champion":"Nhà Vô Địch Từ","sage":"Hiền Nhân Từ","virtuoso":"Cao Thủ Từ","legend":"Huyền Thoại Từ","wizard":"Phù Thủy Từ","grandmaster":"Đại Sư Từ"},
  "zh-CN": {"scout":"单词侦察兵","explorer":"单词探险家","tracker":"单词追踪者","ranger":"单词游侠","guide":"单词向导","master":"单词大师","champion":"单词冠军","sage":"单词贤者","virtuoso":"单词名家","legend":"单词传奇","wizard":"单词魔法师","grandmaster":"单词宗师"},
  "zh-TW": {"scout":"單字偵察兵","explorer":"單字探險家","tracker":"單字追蹤者","ranger":"單字遊俠","guide":"單字嚮導","master":"單字大師","champion":"單字冠軍","sage":"單字賢者","virtuoso":"單字名家","legend":"單字傳奇","wizard":"單字魔法師","grandmaster":"單字宗師"}
} satisfies Record<string, Partial<Record<RankKey, string>>>);


export function rankLabel(key: RankKey, lang: string): string {
  // Per-key fallback to English: a language that predates the long-tail tiers
  // still resolves them (RANK_LABELS.en is complete for every RankKey).
  return RANK_LABELS[lang]?.[key] ?? RANK_LABELS.en[key] ?? key;
}

export type GameCopy = {
  streakTitle: string;
  streakDays: (n: number) => string;
  streakStart: string;
  weeklyTitle: string;
  weeklyProgress: (n: number, goal: number) => string;
  weeklyDone: string;
  rankTitle: string;
  toNext: (n: number) => string;
  topRank: string;
  collected: (n: number) => string;
};

export const GAME_COPY: Record<string, GameCopy> = {
  en: {
    streakTitle: "Day streak",
    streakDays: (n) => (n === 1 ? "1 day in a row" : `${n} days in a row`),
    streakStart: "Look up a word to start a streak",
    weeklyTitle: "Weekly goal",
    weeklyProgress: (n, goal) => `${n} / ${goal} new words`,
    weeklyDone: "Goal complete!",
    rankTitle: "Your rank",
    toNext: (n) => (n === 1 ? "1 more point to level up" : `${n} more points to level up`),
    topRank: "Top rank reached!",
    collected: (n) => (n === 1 ? "1 word collected" : `${n} words collected`),
  },
  he: {
    streakTitle: "רצף ימים",
    streakDays: (n) => (n === 1 ? "יום אחד ברצף" : `${n} ימים ברצף`),
    streakStart: "חפשו מילה כדי להתחיל רצף",
    weeklyTitle: "יעד שבועי",
    weeklyProgress: (n, goal) => `${n} / ${goal} מילים חדשות`,
    weeklyDone: "היעד הושלם!",
    rankTitle: "הדרגה שלך",
    toNext: (n) => (n === 1 ? "עוד נקודה אחת לדרגה הבאה" : `עוד ${n} נקודות לדרגה הבאה`),
    topRank: "הגעת לדרגה הגבוהה ביותר!",
    collected: (n) => (n === 1 ? "מילה אחת באוצר" : `${n} מילים באוצר`),
  },
  ar: {
    streakTitle: "سلسلة",
    streakDays: (n) => (n === 1 ? "يوم واحد متتالٍ" : `${n} أيام متتالية`),
    streakStart: "ابحث عن كلمة لتبدأ سلسلة",
    weeklyTitle: "هذا الأسبوع",
    weeklyProgress: (n, goal) => `${n} / ${goal} كلمات جديدة`,
    weeklyDone: "أكملت هدف الأسبوع!",
    rankTitle: "رتبتك",
    toNext: (n) => (n === 1 ? "نقطة واحدة للترقية" : `${n} نقاط للترقية`),
    topRank: "وصلت إلى أعلى رتبة!",
    collected: (n) => (n === 1 ? "كلمة واحدة في المجموعة" : `${n} كلمات في المجموعة`),
  },
  ru: {
    streakTitle: "Серия",
    streakDays: (n) => (n === 1 ? "1 день подряд" : `${n} дней подряд`),
    streakStart: "Найди слово, чтобы начать серию",
    weeklyTitle: "На этой неделе",
    weeklyProgress: (n, goal) => `${n} / ${goal} новых слов`,
    weeklyDone: "Цель недели выполнена!",
    rankTitle: "Твой ранг",
    toNext: (n) => (n === 1 ? "ещё 1 очко до нового ранга" : `ещё ${n} очк(а/ов) до нового ранга`),
    topRank: "Достигнут высший ранг!",
    collected: (n) => (n === 1 ? "1 слово собрано" : `${n} слов собрано`),
  },
  es: {
    streakTitle: "Racha",
    streakDays: (n) => (n === 1 ? "1 día seguido" : `${n} días seguidos`),
    streakStart: "Busca una palabra para empezar una racha",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palabras nuevas`,
    weeklyDone: "¡Meta de la semana cumplida!",
    rankTitle: "Tu rango",
    toNext: (n) => (n === 1 ? "1 punto más para subir de nivel" : `${n} puntos más para subir de nivel`),
    topRank: "¡Rango máximo alcanzado!",
    collected: (n) => (n === 1 ? "1 palabra reunida" : `${n} palabras reunidas`),
  },
  pt: {
    streakTitle: "Sequência",
    streakDays: (n) => (n === 1 ? "1 dia seguido" : `${n} dias seguidos`),
    streakStart: "Busque uma palavra para começar uma sequência",
    weeklyTitle: "Esta semana",
    weeklyProgress: (n, goal) => `${n} / ${goal} palavras novas`,
    weeklyDone: "Meta da semana concluída!",
    rankTitle: "Seu nível",
    toNext: (n) => (n === 1 ? "mais 1 ponto para subir de nível" : `mais ${n} pontos para subir de nível`),
    topRank: "Nível máximo alcançado!",
    collected: (n) => (n === 1 ? "1 palavra reunida" : `${n} palavras reunidas`),
  },
  fr: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 jour d'affilée" : `${n} jours d'affilée`),
    streakStart: "Cherche un mot pour lancer une série",
    weeklyTitle: "Cette semaine",
    weeklyProgress: (n, goal) => `${n} / ${goal} nouveaux mots`,
    weeklyDone: "Objectif de la semaine atteint !",
    rankTitle: "Ton rang",
    toNext: (n) => (n === 1 ? "encore 1 point pour monter de niveau" : `encore ${n} points pour monter de niveau`),
    topRank: "Rang maximal atteint !",
    collected: (n) => (n === 1 ? "1 mot collecté" : `${n} mots collectés`),
  },
  de: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 Tag in Folge" : `${n} Tage in Folge`),
    streakStart: "Schlag ein Wort nach, um eine Serie zu starten",
    weeklyTitle: "Diese Woche",
    weeklyProgress: (n, goal) => `${n} / ${goal} neue Wörter`,
    weeklyDone: "Wochenziel geschafft!",
    rankTitle: "Dein Rang",
    toNext: (n) => (n === 1 ? "noch 1 Punkt bis zum nächsten Rang" : `noch ${n} Punkte bis zum nächsten Rang`),
    topRank: "Höchster Rang erreicht!",
    collected: (n) => (n === 1 ? "1 Wort gesammelt" : `${n} Wörter gesammelt`),
  },
  cs: {
    streakTitle: "Série",
    streakDays: (n) => (n === 1 ? "1 den v řadě" : `${n} dní v řadě`),
    streakStart: "Vyhledej slovo a začni sérii",
    weeklyTitle: "Tento týden",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týdenní cíl splněn!",
    rankTitle: "Tvoje úroveň",
    toNext: (n) => (n === 1 ? "ještě 1 bod do vyšší úrovně" : `ještě ${n} bodů do vyšší úrovně`),
    topRank: "Nejvyšší úroveň dosažena!",
    collected: (n) => (n === 1 ? "1 slovo nasbíráno" : `${n} slov nasbíráno`),
  },
  sk: {
    streakTitle: "Séria",
    streakDays: (n) => (n === 1 ? "1 deň v rade" : `${n} dní v rade`),
    streakStart: "Vyhľadaj slovo a začni sériu",
    weeklyTitle: "Tento týždeň",
    weeklyProgress: (n, goal) => `${n} / ${goal} nových slov`,
    weeklyDone: "Týždenný cieľ splnený!",
    rankTitle: "Tvoja úroveň",
    toNext: (n) => (n === 1 ? "ešte 1 bod do vyššej úrovne" : `ešte ${n} bodov do vyššej úrovne`),
    topRank: "Najvyššia úroveň dosiahnutá!",
    collected: (n) => (n === 1 ? "1 slovo nazbierané" : `${n} slov nazbieraných`),
  },
  it: {
    streakTitle: "Serie",
    streakDays: (n) => (n === 1 ? "1 giorno di fila" : `${n} giorni di fila`),
    streakStart: "Cerca una parola per iniziare una serie",
    weeklyTitle: "Questa settimana",
    weeklyProgress: (n, goal) => `${n} / ${goal} parole nuove`,
    weeklyDone: "Obiettivo della settimana raggiunto!",
    rankTitle: "Il tuo grado",
    toNext: (n) => (n === 1 ? "ancora 1 punto per salire di livello" : `ancora ${n} punti per salire di livello`),
    topRank: "Grado massimo raggiunto!",
    collected: (n) => (n === 1 ? "1 parola raccolta" : `${n} parole raccolte`),
  },
  ja: {
    streakTitle: "連続",
    streakDays: (n) => `${n}日連続`,
    streakStart: "ことばを調べて連続記録をはじめよう",
    weeklyTitle: "今週",
    weeklyProgress: (n, goal) => `新しいことば ${n} / ${goal}`,
    weeklyDone: "今週の目標を達成！",
    rankTitle: "あなたのランク",
    toNext: (n) => `次のランクまであと ${n} ポイント`,
    topRank: "最高ランクに到達！",
    collected: (n) => `${n} ことばを集めた`,
  },
  hi: {
    streakTitle: "लगातार",
    streakDays: (n) => (n === 1 ? "1 दिन लगातार" : `${n} दिन लगातार`),
    streakStart: "एक शब्द खोजें और सिलसिला शुरू करें",
    weeklyTitle: "इस हफ़्ते",
    weeklyProgress: (n, goal) => `${n} / ${goal} नए शब्द`,
    weeklyDone: "हफ़्ते का लक्ष्य पूरा!",
    rankTitle: "आपकी रैंक",
    toNext: (n) => (n === 1 ? "अगली रैंक के लिए 1 और अंक" : `अगली रैंक के लिए ${n} और अंक`),
    topRank: "सबसे ऊँची रैंक पर पहुँच गए!",
    collected: (n) => (n === 1 ? "1 शब्द जमा" : `${n} शब्द जमा`),
  },
  am: {
    streakTitle: "ተከታታይ",
    streakDays: (n) => (n === 1 ? "1 ቀን በተከታታይ" : `${n} ቀናት በተከታታይ`),
    streakStart: "ተከታታይ ለመጀመር ቃል ፈልግ",
    weeklyTitle: "በዚህ ሳምንት",
    weeklyProgress: (n, goal) => `${n} / ${goal} አዲስ ቃላት`,
    weeklyDone: "የሳምንቱ ግብ ተሳክቷል!",
    rankTitle: "ደረጃህ",
    toNext: (n) => (n === 1 ? "ወደ ቀጣዩ ደረጃ 1 ተጨማሪ ነጥብ" : `ወደ ቀጣዩ ደረጃ ${n} ተጨማሪ ነጥቦች`),
    topRank: "ከፍተኛውን ደረጃ ደርሰሃል!",
    collected: (n) => (n === 1 ? "1 ቃል ተሰብስቧል" : `${n} ቃላት ተሰብስበዋል`),
  },
  uk: {
    streakTitle: "Серія",
    streakDays: (n) => (n === 1 ? "1 день поспіль" : `${n} днів поспіль`),
    streakStart: "Знайди слово, щоб почати серію",
    weeklyTitle: "Цього тижня",
    weeklyProgress: (n, goal) => `${n} / ${goal} нових слів`,
    weeklyDone: "Ціль тижня виконано!",
    rankTitle: "Твій ранг",
    toNext: (n) => (n === 1 ? "ще 1 бал до нового рангу" : `ще ${n} балів до нового рангу`),
    topRank: "Досягнуто найвищий ранг!",
    collected: (n) => (n === 1 ? "1 слово зібрано" : `${n} слів зібрано`),
  },
  tr: {
    streakTitle: "Seri",
    streakDays: (n) => `üst üste ${n} gün`,
    streakStart: "Bir seri başlatmak için kelime ara",
    weeklyTitle: "Bu hafta",
    weeklyProgress: (n, goal) => `${n} / ${goal} yeni kelime`,
    weeklyDone: "Haftalık hedef tamam!",
    rankTitle: "Seviyen",
    toNext: (n) => `bir üst seviye için ${n} puan daha`,
    topRank: "En yüksek seviyeye ulaştın!",
    collected: (n) => `${n} kelime toplandı`,
  },
  pl: {
    streakTitle: "Seria",
    streakDays: (n) => (n === 1 ? "1 dzień z rzędu" : `${n} dni z rzędu`),
    streakStart: "Wyszukaj słowo, aby zacząć serię",
    weeklyTitle: "W tym tygodniu",
    weeklyProgress: (n, goal) => `${n} / ${goal} nowych słów`,
    weeklyDone: "Cel tygodnia osiągnięty!",
    rankTitle: "Twoja ranga",
    toNext: (n) => (n === 1 ? "jeszcze 1 punkt do wyższej rangi" : `jeszcze ${n} punktów do wyższej rangi`),
    topRank: "Osiągnięto najwyższą rangę!",
    collected: (n) => (n === 1 ? "1 słowo zebrane" : `${n} słów zebranych`),
  },
  fa: {
    streakTitle: "زنجیره",
    streakDays: (n) => (n === 1 ? "۱ روز پیاپی" : `${n} روز پیاپی`),
    streakStart: "برای شروع زنجیره یک واژه جست‌وجو کن",
    weeklyTitle: "این هفته",
    weeklyProgress: (n, goal) => `${n} / ${goal} واژه‌ی جدید`,
    weeklyDone: "هدف هفته کامل شد!",
    rankTitle: "رتبه‌ی تو",
    toNext: (n) => (n === 1 ? "۱ امتیاز دیگر تا رتبه‌ی بعدی" : `${n} امتیاز دیگر تا رتبه‌ی بعدی`),
    topRank: "به بالاترین رتبه رسیدی!",
    collected: (n) => (n === 1 ? "۱ واژه جمع شد" : `${n} واژه جمع شد`),
  },
  id: {
    streakTitle: "Beruntun",
    streakDays: (n) => `${n} hari beruntun`,
    streakStart: "Cari sebuah kata untuk memulai rentetan",
    weeklyTitle: "Minggu ini",
    weeklyProgress: (n, goal) => `${n} / ${goal} kata baru`,
    weeklyDone: "Target minggu ini tercapai!",
    rankTitle: "Peringkatmu",
    toNext: (n) => `${n} poin lagi untuk naik peringkat`,
    topRank: "Peringkat tertinggi tercapai!",
    collected: (n) => `${n} kata terkumpul`,
  },
  nl: {
    streakTitle: "Reeks",
    streakDays: (n) => (n === 1 ? "1 dag op rij" : `${n} dagen op rij`),
    streakStart: "Zoek een woord op om een reeks te starten",
    weeklyTitle: "Deze week",
    weeklyProgress: (n, goal) => `${n} / ${goal} nieuwe woorden`,
    weeklyDone: "Weekdoel gehaald!",
    rankTitle: "Jouw rang",
    toNext: (n) => (n === 1 ? "nog 1 punt tot de volgende rang" : `nog ${n} punten tot de volgende rang`),
    topRank: "Hoogste rang bereikt!",
    collected: (n) => (n === 1 ? "1 woord verzameld" : `${n} woorden verzameld`),
  },
  el: {
    streakTitle: "Σερί",
    streakDays: (n) => (n === 1 ? "1 μέρα στη σειρά" : `${n} μέρες στη σειρά`),
    streakStart: "Ψάξε μια λέξη για να ξεκινήσεις σερί",
    weeklyTitle: "Αυτή την εβδομάδα",
    weeklyProgress: (n, goal) => `${n} / ${goal} νέες λέξεις`,
    weeklyDone: "Ο εβδομαδιαίος στόχος ολοκληρώθηκε!",
    rankTitle: "Η βαθμίδα σου",
    toNext: (n) => (n === 1 ? "1 πόντος ακόμα για την επόμενη βαθμίδα" : `${n} πόντοι ακόμα για την επόμενη βαθμίδα`),
    topRank: "Έφτασες στην ανώτατη βαθμίδα!",
    collected: (n) => (n === 1 ? "1 λέξη μαζεύτηκε" : `${n} λέξεις μαζεύτηκαν`),
  },
  zu: {
    streakTitle: "Ukulandelana",
    streakDays: (n) => (n === 1 ? "usuku olu-1 ngokulandelana" : `izinsuku ezi-${n} ngokulandelana`),
    streakStart: "Sesha igama ukuze uqale ukulandelana",
    weeklyTitle: "Kuleli sonto",
    weeklyProgress: (n, goal) => `${n} / ${goal} amagama amasha`,
    weeklyDone: "Umgomo weviki uphelele!",
    rankTitle: "Izinga lakho",
    toNext: (n) => (n === 1 ? "iphuzu elilodwa ukuze ukhuphuke izinga" : `amaphuzu angu-${n} ukuze ukhuphuke izinga`),
    topRank: "Ufinyelele izinga eliphezulu!",
    collected: (n) => (n === 1 ? "igama eli-1 liqoqiwe" : `amagama angu-${n} aqoqiwe`),
  },
};

// 11 store-locale languages (added 2026-08-22): native streak/weekly/rank copy.
Object.assign(GAME_COPY, {
  "af": {
    streakTitle: "Dagreeks",
    streakDays: (n) => (n === 1 ? "1 dag op 'n ry" : "" + n + " dae op 'n ry"),
    streakStart: "Soek 'n woord op om 'n reeks te begin",
    weeklyTitle: "Weeklikse doel",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " nuwe woorde",
    weeklyDone: "Doel voltooi!",
    rankTitle: "Jou rang",
    toNext: (n) => (n === 1 ? "1 punt meer om op te gradeer" : "" + n + " punte meer om op te gradeer"),
    topRank: "Boonste rang bereik!",
    collected: (n) => (n === 1 ? "1 woord versamel" : "" + n + " woorde versamel"),
  },
  "bn": {
    streakTitle: "ধারাবাহিক দিন",
    streakDays: (n) => (n === 1 ? "টানা 1 দিন" : "টানা " + n + " দিন"),
    streakStart: "ধারা শুরু করতে একটি শব্দ খোঁজো",
    weeklyTitle: "সাপ্তাহিক লক্ষ্য",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " নতুন শব্দ",
    weeklyDone: "লক্ষ্য পূর্ণ!",
    rankTitle: "তোমার র‍্যাঙ্ক",
    toNext: (n) => (n === 1 ? "লেভেল বাড়াতে আর 1 পয়েন্ট" : "লেভেল বাড়াতে আর " + n + " পয়েন্ট"),
    topRank: "সর্বোচ্চ র‍্যাঙ্কে পৌঁছেছ!",
    collected: (n) => (n === 1 ? "1টি শব্দ সংগ্রহ" : "" + n + "টি শব্দ সংগ্রহ"),
  },
  "da": {
    streakTitle: "Dagsrække",
    streakDays: (n) => (n === 1 ? "1 dag i træk" : "" + n + " dage i træk"),
    streakStart: "Slå et ord op for at starte en række",
    weeklyTitle: "Ugentligt mål",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " nye ord",
    weeklyDone: "Mål nået!",
    rankTitle: "Din rang",
    toNext: (n) => (n === 1 ? "1 point mere for at stige et niveau" : "" + n + " point mere for at stige et niveau"),
    topRank: "Højeste rang nået!",
    collected: (n) => (n === 1 ? "1 ord samlet" : "" + n + " ord samlet"),
  },
  "fil": {
    streakTitle: "Sunod-sunod na araw",
    streakDays: (n) => (n === 1 ? "1 araw nang sunod-sunod" : "" + n + " araw nang sunod-sunod"),
    streakStart: "Maghanap ng salita para magsimula ng streak",
    weeklyTitle: "Lingguhang layunin",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " bagong salita",
    weeklyDone: "Tapos na ang layunin!",
    rankTitle: "Ang iyong ranggo",
    toNext: (n) => (n === 1 ? "1 puntos na lang para umangat" : "" + n + " puntos na lang para umangat"),
    topRank: "Nasa pinakamataas na ranggo!",
    collected: (n) => (n === 1 ? "1 salitang nakolekta" : "" + n + " salitang nakolekta"),
  },
  "hu": {
    streakTitle: "Napi sorozat",
    streakDays: (n) => (n === 1 ? "1 nap egymás után" : "" + n + " nap egymás után"),
    streakStart: "Keress egy szót a sorozat indításához",
    weeklyTitle: "Heti cél",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " új szó",
    weeklyDone: "Cél teljesítve!",
    rankTitle: "A rangod",
    toNext: (n) => (n === 1 ? "Még 1 pont a szintlépéshez" : "Még " + n + " pont a szintlépéshez"),
    topRank: "Elérted a legmagasabb rangot!",
    collected: (n) => (n === 1 ? "1 szó összegyűjtve" : "" + n + " szó összegyűjtve"),
  },
  "ko": {
    streakTitle: "연속 일수",
    streakDays: (n) => (n === 1 ? "" + n + "일 연속" : "" + n + "일 연속"),
    streakStart: "단어를 검색해 연속 기록을 시작하세요",
    weeklyTitle: "주간 목표",
    weeklyProgress: (n, goal) => "새 단어 " + n + " / " + goal + "개",
    weeklyDone: "목표 달성!",
    rankTitle: "내 등급",
    toNext: (n) => (n === 1 ? "레벨업까지 " + n + "점" : "레벨업까지 " + n + "점"),
    topRank: "최고 등급 달성!",
    collected: (n) => (n === 1 ? "단어 " + n + "개 수집" : "단어 " + n + "개 수집"),
  },
  "sw": {
    streakTitle: "Mfululizo wa siku",
    streakDays: (n) => (n === 1 ? "Siku 1 mfululizo" : "Siku " + n + " mfululizo"),
    streakStart: "Tafuta neno ili kuanza mfululizo",
    weeklyTitle: "Lengo la wiki",
    weeklyProgress: (n, goal) => "Maneno mapya " + n + " / " + goal + "",
    weeklyDone: "Lengo limekamilika!",
    rankTitle: "Cheo chako",
    toNext: (n) => (n === 1 ? "Pointi 1 zaidi ili kupanda ngazi" : "Pointi " + n + " zaidi ili kupanda ngazi"),
    topRank: "Umefika cheo cha juu!",
    collected: (n) => (n === 1 ? "Neno 1 limekusanywa" : "Maneno " + n + " yamekusanywa"),
  },
  "th": {
    streakTitle: "จำนวนวันต่อเนื่อง",
    streakDays: (n) => (n === 1 ? "ต่อเนื่อง " + n + " วัน" : "ต่อเนื่อง " + n + " วัน"),
    streakStart: "ค้นหาคำเพื่อเริ่มสถิติต่อเนื่อง",
    weeklyTitle: "เป้าหมายรายสัปดาห์",
    weeklyProgress: (n, goal) => "คำใหม่ " + n + " / " + goal + " คำ",
    weeklyDone: "ทำเป้าหมายสำเร็จ!",
    rankTitle: "อันดับของคุณ",
    toNext: (n) => (n === 1 ? "อีก " + n + " แต้มเพื่อเลื่อนระดับ" : "อีก " + n + " แต้มเพื่อเลื่อนระดับ"),
    topRank: "ถึงอันดับสูงสุดแล้ว!",
    collected: (n) => (n === 1 ? "เก็บได้ " + n + " คำ" : "เก็บได้ " + n + " คำ"),
  },
  "vi": {
    streakTitle: "Chuỗi ngày",
    streakDays: (n) => (n === 1 ? "" + n + " ngày liên tiếp" : "" + n + " ngày liên tiếp"),
    streakStart: "Tra một từ để bắt đầu chuỗi",
    weeklyTitle: "Mục tiêu tuần",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " từ mới",
    weeklyDone: "Hoàn thành mục tiêu!",
    rankTitle: "Cấp bậc của bạn",
    toNext: (n) => (n === 1 ? "Thêm " + n + " điểm để lên cấp" : "Thêm " + n + " điểm để lên cấp"),
    topRank: "Đã đạt cấp cao nhất!",
    collected: (n) => (n === 1 ? "Đã thu thập " + n + " từ" : "Đã thu thập " + n + " từ"),
  },
  "zh-CN": {
    streakTitle: "连续天数",
    streakDays: (n) => (n === 1 ? "连续 " + n + " 天" : "连续 " + n + " 天"),
    streakStart: "查一个单词开始连续记录",
    weeklyTitle: "每周目标",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " 个新单词",
    weeklyDone: "目标完成！",
    rankTitle: "你的等级",
    toNext: (n) => (n === 1 ? "再得 " + n + " 分升级" : "再得 " + n + " 分升级"),
    topRank: "已达最高等级！",
    collected: (n) => (n === 1 ? "已收集 " + n + " 个单词" : "已收集 " + n + " 个单词"),
  },
  "zh-TW": {
    streakTitle: "連續天數",
    streakDays: (n) => (n === 1 ? "連續 " + n + " 天" : "連續 " + n + " 天"),
    streakStart: "查一個單字開始連續紀錄",
    weeklyTitle: "每週目標",
    weeklyProgress: (n, goal) => "" + n + " / " + goal + " 個新單字",
    weeklyDone: "目標完成！",
    rankTitle: "你的等級",
    toNext: (n) => (n === 1 ? "再得 " + n + " 分升級" : "再得 " + n + " 分升級"),
    topRank: "已達最高等級！",
    collected: (n) => (n === 1 ? "已收集 " + n + " 個單字" : "已收集 " + n + " 個單字"),
  },
} satisfies Record<string, GameCopy>);


export function gameCopy(lang: string): GameCopy {
  return GAME_COPY[lang] ?? GAME_COPY.en;
}
