import MORE from "./plan-copy-i18n.json";

/**
 * Copy for the new plan structure (Gadi 2026-10-06): Free, Individual,
 * Family. Hebrew and English are written here; the other UI languages come
 * from plan-copy-i18n.json (scripts/plan-copy-i18n.mjs), English fallback.
 * {n} / {max} / {price} are filled by planCopy().
 */
export const PLAN_COPY = {
  en: {
    nbFreeCount: "{n} of {max} words in your free notebook",
    nbFreeFull: "Your free notebook is full ({max} words). With Individual, every word you look up is saved.",
    nbFreeCta: "See Individual",
    prHead: "For you and your family",
    prBasicSub: "For one person",
    prIndSub: "For one person, every tool",
    prFamSub: "Up to 5 children, plus parents",
    prBasicCta: "Start free",
    prTrialCta: "Try 14 days free",
    prFamBadge: "Best for families",
    prYearlyPerMonth: "About {price} a month",
    prRowSearches: "Word lookups",
    prSearchesBasic: "10 a day",
    prUnlimited: "Unlimited",
    prRowCore: "Every meaning, examples, idioms and the word's origin",
    prRowNotebook: "Word notebook",
    prNotebookBasic: "Up to 30 words",
    prRowImages: "A picture for every meaning",
    prRowContext: "The right meaning from a sentence",
    prRowRead: "Every Word: photograph a page, tap any word",
    prRowSay: "Say it: pronunciation practice with a score",
    prRowCompose: "Compose a sentence and get feedback",
    prRowPractice: "Smart practice, games and quizzes",
    prRowCompare: "Compare similar words",
    prRowKids: "Kids Mode: simple explanations for children",
    prRowChildren: "Up to 5 children, each with their own space",
    prRowParent: "Parent board and an alert for every word",
    prRowDictation: "School dictation practice",
    modalIsInd: "Part of the Individual plan",
    modalIsFam: "Part of the Family plan",
    modalPerMonth: "{price} a month",
    wallAnonBody: "A quick free sign-up opens up to 10 lookups a day, with every meaning, examples, idioms and the word's origin.",
    wallBasicBody: "A free account includes 10 lookups a day. The limit resets tomorrow, or try Individual for unlimited lookups, pictures and every learning tool.",
    wallCta: "See Individual",
    sayPaidBody: "Say it is part of the Individual, Family and Schools plans.",
    kidsGate: "Kids Mode is part of the Family plan.",
    audTitle: "Who is Gadit for?",
    audSub: "So we can show you what fits.",
    audMe: "For me",
    audChild: "For my child",
    audClass: "For a class or a school",
    audSkip: "Skip",
    featFamPeople: "Every child gets every tool, with Kids Mode. The parent pays once for the whole family.",
    demoPlusMore: "And more: quizzes, games and comparing words",
    partnersCalcNote: "Estimate based on the Individual plan and a 25% rate. Yearly, Family and Schools customers raise it.",
    helpSwitchQ: "How do I switch to Family?",
    helpSwitchA1: "Open your Account page and tap \"Switch to Family\". Your current subscription is updated on the same card, without entering it again.",
    helpSwitchA2: "Stripe works out the difference for the days left in the current period, so you only pay the difference.",
    helpChargeA1: "Charges appear as GADIT or GADIT.APP. Individual is $3.99 a month or $39.99 a year, and Family is $5.99 a month or $59 a year. In Israel the charge is in shekels: ₪14.90 or ₪149 for Individual, ₪19.90 or ₪199 for Family. Subscriptions from before October 2026 keep the price they started with. If the amount doesn't match, it may be from a different service.",
    helpCompareQ: "What's the difference between Basic, Individual and Family?",
    helpCompareA1: "Basic (free): up to 10 word lookups a day, every meaning, examples, idioms, the word's origin, and a notebook of up to 30 words.",
    helpCompareA2: "Individual ($3.99 a month or $39.99 a year, ₪14.90 or ₪149 in Israel): one person, every tool. Unlimited lookups, a picture for every meaning, the right meaning from a sentence, Every Word, Say it, compose a sentence with feedback, smart practice, games and quizzes, and comparing similar words.",
    remSubject: "Hi {name}, your Gadit trial ends in two days",
    remBody: "Hi {name},\n\nYour free trial of Gadit ends on {date}.\n\n## What happens then\nOn that day your card is charged {amount} {cycle} for {plan}.\n\nThere is nothing you need to do to keep going.\n\n## How to cancel\nYou can cancel any time before {date}, and nothing is charged.\n\n1. Open your [Account page](/account).\n2. Tap \"Manage billing\".\n3. On the page that opens, choose to cancel the subscription.",
    remCta: "Go to my account",
    remCycleMonth: "a month",
    remCycleYear: "a year",
    // Upgrade email for people who use Gadit in the Android (Play) app, where
    // nothing can be bought (Gadi 2026-10-06). Sent by email, outside the app.
    pupSubject: "How to upgrade your Gadit account",
    pupBody: "Hi {name},\n\nThanks for using Gadit on Android.\n\nUpgrades are not available inside the app, so here is a direct link that opens in your browser.\n\n## Family\n\nFor parents and children.\n\nUp to 5 kids, each with their own notebook, Kids Mode and a parent dashboard.\n\n## Individual\n\nFor one person.\n\nUnlimited lookups and every tool.\n\nBoth start with 14 days free.\n\nYou can cancel any time before the trial ends, and nothing is charged.\n\nOnce you subscribe, the app updates on its own.\n\nJust sign in with the same account.",
    pupCta: "See the plans",
    helpCompareA3: "Family ($5.99 a month or $59 a year, ₪19.90 or ₪199 in Israel): everything in Individual for up to 5 children and both parents, plus Kids Mode, a space of its own for every child, the parent board with word alerts, and dictation practice.",
    famSingleChild: "Just one learner at home? Individual is {price} a month. For a little more, Family adds up to 5 children.",
  },
  he: {
    nbFreeCount: "{n} מתוך {max} מילים במחברת החינמית",
    nbFreeFull: "המחברת החינמית מלאה ({max} מילים). ב-Individual כל מילה שמחפשים נשמרת.",
    nbFreeCta: "להכיר את Individual",
    prHead: "לך ולמשפחה",
    prBasicSub: "לאדם אחד",
    prIndSub: "לאדם אחד, כל הכלים",
    prFamSub: "עד 5 ילדים, וגם ההורים",
    prBasicCta: "להתחיל בחינם",
    prTrialCta: "14 יום ניסיון חינם",
    prFamBadge: "הכי מתאים למשפחות",
    prYearlyPerMonth: "כ-{price} לחודש",
    prRowSearches: "חיפושי מילים",
    prSearchesBasic: "10 ביום",
    prUnlimited: "ללא הגבלה",
    prRowCore: "כל המשמעויות, דוגמאות, ניבים ומקור המילה",
    prRowNotebook: "מחברת מילים",
    prNotebookBasic: "עד 30 מילים",
    prRowImages: "תמונה לכל משמעות",
    prRowContext: "המשמעות הנכונה לפי המשפט",
    prRowRead: "כל מילה: מצלמים דף ולוחצים על כל מילה",
    prRowSay: "תגיד את זה: תרגול הגייה עם ציון",
    prRowCompose: "חברו משפט וקבלו משוב",
    prRowPractice: "תרגול חכם, משחקים וחידונים",
    prRowCompare: "השוואת מילים דומות",
    prRowKids: "מצב ילדים: הסבר פשוט לילדים",
    prRowChildren: "עד 5 ילדים, לכל אחד אזור משלו",
    prRowParent: "לוח הורה והתראה על כל מילה",
    prRowDictation: "תרגול הכתבה של בית הספר",
    modalIsInd: "חלק מ-Individual",
    modalIsFam: "חלק מ-Family",
    modalPerMonth: "{price} לחודש",
    wallAnonBody: "הרשמה מהירה בחינם פותחת עד 10 חיפושים ביום, עם כל המשמעויות, דוגמאות, ניבים ומקור המילה.",
    wallBasicBody: "חשבון חינמי כולל 10 חיפושים ביום. המכסה מתאפסת מחר, או שאפשר לנסות את Individual: חיפושים ללא הגבלה, תמונות וכל כלי הלימוד.",
    wallCta: "להכיר את Individual",
    sayPaidBody: "תגיד את זה כלול ב-Individual, ב-Family ובמנוי לבתי ספר.",
    kidsGate: "מצב ילדים כלול במנוי Family.",
    audTitle: "בשביל מי Gadit?",
    audSub: "כדי שנוכל להראות לך את מה שמתאים.",
    audMe: "בשבילי",
    audChild: "בשביל הילד שלי",
    audClass: "לכיתה או לבית ספר",
    audSkip: "דילוג",
    featFamPeople: "כל ילד מקבל את כל הכלים, עם מצב ילדים. ההורה משלם פעם אחת על כל המשפחה.",
    demoPlusMore: "ועוד: חידונים, משחקים והשוואת מילים",
    partnersCalcNote: "הערכה לפי מנוי Individual ועמלה של 25%. לקוחות שנתיים, Family ובתי ספר מעלים אותה.",
    helpSwitchQ: "איך עוברים ל-Family?",
    helpSwitchA1: "נכנסים לעמוד החשבון ולוחצים על \"מעבר ל-Family\". המנוי הנוכחי מתעדכן על אותו כרטיס, בלי להזין אותו מחדש.",
    helpSwitchA2: "Stripe מחשב את ההפרש לפי הימים שנשארו בתקופה הנוכחית, ומשלמים רק את ההפרש.",
    helpChargeA1: "החיובים מופיעים בשם GADIT או GADIT.APP. בישראל החיוב בשקלים: Individual עולה ₪14.90 לחודש או ₪149 לשנה, ו-Family עולה ₪19.90 לחודש או ₪199 לשנה. מחוץ לישראל: $3.99 או $39.99 ל-Individual, ו-$5.99 או $59 ל-Family. מנויים מלפני אוקטובר 2026 נשארים במחיר שבו התחילו. אם הסכום לא מתאים, ייתכן שהחיוב משירות אחר.",
    helpCompareQ: "מה ההבדל בין Basic, Individual ו-Family?",
    helpCompareA1: "Basic (חינם): עד 10 חיפושי מילים ביום, כל המשמעויות, דוגמאות, ניבים, מקור המילה, ומחברת עד 30 מילים.",
    helpCompareA2: "Individual (₪14.90 לחודש או ₪149 לשנה): לאדם אחד, כל הכלים. חיפושים ללא הגבלה, תמונה לכל משמעות, המשמעות הנכונה לפי המשפט, כל מילה, תגיד את זה, חברו משפט עם משוב, תרגול חכם, משחקים וחידונים, והשוואת מילים דומות.",
    remSubject: "היי {name}, בעוד יומיים מסתיימת תקופת הניסיון ב-Gadit",
    remBody: "היי {name},\n\nתקופת הניסיון החינמית שלך ב-Gadit מסתיימת ב-{date}.\n\n## מה קורה אז\nבאותו יום הכרטיס שלך יחויב ב-{amount} {cycle}, עבור {plan}.\n\nלא צריך לעשות כלום כדי להמשיך.\n\n## איך מבטלים\nאפשר לבטל בכל רגע לפני {date}, ואז לא יהיה שום חיוב.\n\n1. נכנסים ל[עמוד החשבון](/account).\n2. לוחצים על \"ניהול חיוב\".\n3. בעמוד שנפתח בוחרים לבטל את המנוי.",
    remCta: "לעמוד החשבון",
    remCycleMonth: "לחודש",
    remCycleYear: "לשנה",
    pupSubject: "איך משדרגים את החשבון ב-Gadit",
    pupBody: "היי {name},\n\nתודה שבחרת להשתמש ב-Gadit באנדרואיד.\n\nבתוך האפליקציה אי אפשר לשדרג, ולכן שלחנו לך קישור ישיר שנפתח בדפדפן.\n\n## Family\n\nלהורים ולילדים.\n\nעד 5 ילדים, לכל ילד מחברת משלו, מצב ילדים ולוח הורה.\n\n## Individual\n\nלאדם אחד.\n\nחיפושים ללא הגבלה וכל הכלים.\n\nבשני המסלולים 14 הימים הראשונים חינם.\n\nאפשר לבטל בכל רגע לפני סוף הניסיון, ולא יהיה שום חיוב.\n\nאחרי ההרשמה האפליקציה מתעדכנת לבד.\n\nרק צריך להתחבר עם אותו חשבון.",
    pupCta: "לראות את המסלולים",
    helpCompareA3: "Family (₪19.90 לחודש או ₪199 לשנה): כל מה שיש ב-Individual לעד 5 ילדים ולשני ההורים, ובנוסף מצב ילדים, אזור משלו לכל ילד, לוח הורה עם התראות על מילים, ותרגול הכתבה.",
    famSingleChild: "יש בבית לומד אחד? Individual עולה {price} לחודש. בעוד קצת, Family מצרף עד 5 ילדים.",
  },
};

export type PlanCopyKey = keyof typeof PLAN_COPY.en;
const OTHER = MORE as Record<string, Partial<Record<PlanCopyKey, string>>>;

export function planCopy(lang: string, key: PlanCopyKey, vars: Record<string, string | number> = {}): string {
  const base =
    (lang === "he" ? PLAN_COPY.he[key] : lang === "en" ? PLAN_COPY.en[key] : OTHER[lang]?.[key]) ?? PLAN_COPY.en[key];
  return base.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

/** Free accounts keep up to this many words in the notebook. */
export const FREE_NOTEBOOK_MAX = 30;
